import { validEnvelope, validKeyMaterial, validateUsername, validAttachmentId, validAttachmentEnvelope, validInviteCode, MAX_ATTACHMENT_CIPHERTEXT } from '../../../shared/contract.mjs';

interface Env { DB:D1Database; ASSETS:Fetcher; ATTACHMENTS:R2Bucket; INVITE_CODE?:string }
type User={id:string;username:string;password_hash:string;password_salt:string;kdf:string;wrapped_key:string};
type Session=User&{user_id:string;id_hash:string;csrf_hash:string;expires_at:number};
type Envelope={id:string;type:'account'|'website'|'note';version:number;iv:string;ciphertext:string};
const COOKIE='pv_session', SESSION_SECONDS=28800, MAX_BODY=2_000_000, LOGIN_WINDOW=60_000, LOGIN_LIMIT=10, MAX_BACKUP_ATTACHMENTS=20*1024*1024, MAX_BACKUP_JSON=30*1024*1024, MAX_WORKER_UPLOAD=20*1024*1024+16;
const enc=new TextEncoder();
export const R2_QUOTAS={storageBytes:8*1024**3,classA:800_000,classB:8_000_000} as const;
export const utcMonth=(date=new Date())=>date.toISOString().slice(0,7);
class QuotaExceeded extends Error{quota:'storage'|'class_a'|'class_b';constructor(quota:'storage'|'class_a'|'class_b'){super('quota_exceeded');this.quota=quota}}
async function reserveOperation(env:Env,kind:'class_a'|'class_b',count=1){const month=utcMonth();await env.DB.prepare('INSERT INTO r2_monthly_usage(month,class_a,class_b) VALUES(?,0,0) ON CONFLICT(month) DO NOTHING').bind(month).run();const column=kind==='class_a'?'class_a':'class_b',limit=kind==='class_a'?R2_QUOTAS.classA:R2_QUOTAS.classB;const result=await env.DB.prepare(`UPDATE r2_monthly_usage SET ${column}=${column}+? WHERE month=? AND ${column}+?<=?`).bind(count,month,count,limit).run();if(!result.meta.changes)throw new QuotaExceeded(kind)}
async function ensureStorageCounter(env:Env){const total=Number((await env.DB.prepare('SELECT COALESCE(SUM(ciphertext_size),0) AS total FROM attachments').first<{total:number}>())?.total||0);await env.DB.prepare('INSERT INTO r2_storage_usage(id,reserved_bytes) VALUES(1,?) ON CONFLICT(id) DO UPDATE SET reserved_bytes=MAX(reserved_bytes,excluded.reserved_bytes)').bind(total).run()}
async function reserveStorage(env:Env,delta:number){await ensureStorageCounter(env);const result=await env.DB.prepare('UPDATE r2_storage_usage SET reserved_bytes=reserved_bytes+? WHERE id=1 AND reserved_bytes+?>=0 AND reserved_bytes+?<=?').bind(delta,delta,delta,R2_QUOTAS.storageBytes).run();if(!result.meta.changes)throw new QuotaExceeded('storage')}
const SECURITY_HEADERS={
 'content-security-policy':"default-src 'self'; script-src 'self'; style-src 'self'; img-src 'self' data: blob:; media-src 'self' blob:; connect-src 'self'; object-src 'none'; base-uri 'none'; form-action 'self'; frame-ancestors 'none'",
 'permissions-policy':'camera=(), microphone=(), geolocation=(), payment=(), usb=()',
 'referrer-policy':'no-referrer',
 'strict-transport-security':'max-age=63072000; includeSubDomains; preload',
 'x-content-type-options':'nosniff',
 'x-frame-options':'DENY'
} as const;
const json=(value:unknown,status=200,headers:HeadersInit={})=>Response.json(value,{status,headers:{...SECURITY_HEADERS,'cache-control':'no-store',...headers}});
async function asset(req:Request,env:Env){const response=await env.ASSETS.fetch(req),headers=new Headers(response.headers);for(const [key,value] of Object.entries(SECURITY_HEADERS))headers.set(key,value);return new Response(response.body,{status:response.status,statusText:response.statusText,headers})}
const error=(status:number,code:string)=>json({error:code},status);
const b64=(bytes:ArrayBuffer|Uint8Array)=>{const a=bytes instanceof Uint8Array?bytes:new Uint8Array(bytes);let s='';for(const x of a)s+=String.fromCharCode(x);return btoa(s).replaceAll('+','-').replaceAll('/','_').replace(/=+$/,'')};
const random=(n=32)=>{const x=new Uint8Array(n);crypto.getRandomValues(x);return b64(x)};
const digest=async(value:string)=>b64(await crypto.subtle.digest('SHA-256',enc.encode(value)));
const digestBytes=async(value:ArrayBuffer)=>b64(await crypto.subtle.digest('SHA-256',value));
const bytesToB64=(value:ArrayBuffer)=>{let out='';for(const x of new Uint8Array(value))out+=String.fromCharCode(x);return btoa(out)};
const b64ToBytes=(value:string)=>{try{return Uint8Array.from(atob(value),c=>c.charCodeAt(0))}catch{return null}};
const passwordHash=async(password:string,salt:string)=>b64(await crypto.subtle.deriveBits({name:'PBKDF2',hash:'SHA-256',salt:enc.encode(salt),iterations:100_000},await crypto.subtle.importKey('raw',enc.encode(password),'PBKDF2',false,['deriveBits']),256));
const equal=(a:string,b:string)=>{if(a.length!==b.length)return false;let x=0;for(let i=0;i<a.length;i++)x|=a.charCodeAt(i)^b.charCodeAt(i);return x===0};
const inviteMatches=async(a:string,b:string)=>equal(await digest(a),await digest(b));
async function body(req:Request){const length=Number(req.headers.get('content-length')||0);if(length>MAX_BODY)throw new RangeError();const text=await req.text();if(text.length>MAX_BODY)throw new RangeError();return JSON.parse(text||'{}') as Record<string,unknown>}
async function limitedJson(req:Request,limit:number){const reader=req.body?.getReader();if(!reader)return {};const chunks:Uint8Array[]=[];let size=0;for(;;){const {done,value}=await reader.read();if(done)break;size+=value.byteLength;if(size>limit){await reader.cancel();throw new RangeError()}chunks.push(value)}const bytes=new Uint8Array(size);let offset=0;for(const chunk of chunks){bytes.set(chunk,offset);offset+=chunk.byteLength}return JSON.parse(new TextDecoder().decode(bytes)||'{}') as any}
const validPassword=(x:unknown)=>typeof x==='string'&&x.length>=12&&x.length<=1024;
const validKey=(x:Record<string,unknown>)=>validKeyMaterial(x);
const material=(u:{kdf:string;wrapped_key:string})=>({kdf:JSON.parse(u.kdf),wrappedKey:JSON.parse(u.wrapped_key)});
function cookie(req:Request){for(const part of (req.headers.get('cookie')||'').split(';')){const [k,...v]=part.trim().split('=');if(k===COOKIE)return v.join('=')}return null}
async function session(req:Request,env:Env){const token=cookie(req);if(!token)return null;return env.DB.prepare('SELECT s.id_hash,s.user_id,s.csrf_hash,s.expires_at,u.id,u.username,u.password_hash,u.password_salt,u.kdf,u.wrapped_key FROM sessions s JOIN users u ON u.id=s.user_id WHERE s.id_hash = ? AND s.expires_at > ?').bind(await digest(token),Date.now()).first<Session>()}
async function safe(req:Request,s:Session){const origin=req.headers.get('origin'),expected=new URL(req.url).origin,token=req.headers.get('x-csrf-token');return origin===expected&&!!token&&equal(await digest(token),s.csrf_hash)}
async function rateLimited(env:Env,key:string){const cutoff=Date.now()-LOGIN_WINDOW;await env.DB.prepare('DELETE FROM login_attempts WHERE attempted_at < ?').bind(cutoff).run();const row=await env.DB.prepare('SELECT COUNT(*) AS count FROM login_attempts WHERE key = ? AND attempted_at > ?').bind(key,cutoff).first<{count:number}>();return Number(row?.count||0)>=LOGIN_LIMIT}
const envelope=(x:Record<string,unknown>,id?:string):Envelope|null=>{const y={...x,...(id?{id}:{})};return Object.keys(y).every(k=>['id','type','version','iv','ciphertext'].includes(k))&&validEnvelope(y)?y as Envelope:null};

export default {async fetch(req:Request,env:Env):Promise<Response>{
 try{
  const u=new URL(req.url),p=u.pathname;
  if(!p.startsWith('/api/'))return asset(req,env);
  if(req.method==='GET'&&p==='/api/health')return json({ok:true,backend:'d1'});
  if(req.method==='POST'&&p==='/api/register'){
   const x=await body(req),key=req.headers.get('CF-Connecting-IP')||'unknown';if(!validInviteCode(env.INVITE_CODE))return error(503,'registration_unavailable');const now=Date.now();await env.DB.prepare('DELETE FROM invite_attempts WHERE attempted_at < ?').bind(now-60_000).run();const attempts=await env.DB.prepare('SELECT COUNT(*) AS count FROM invite_attempts WHERE key=? AND attempted_at>?').bind(key,now-60_000).first<{count:number}>();if((attempts?.count||0)>=10)return error(429,'rate_limited');if(!validInviteCode(x.inviteCode)||!await inviteMatches(x.inviteCode as string,env.INVITE_CODE as string)){await env.DB.prepare('INSERT INTO invite_attempts(key,attempted_at) VALUES(?,?)').bind(key,now).run();return error(403,'invalid_invite')}const name=validateUsername(x.username);if(!name.valid)return error(400,'invalid_username');if(!validPassword(x.password)||!validKey(x))return error(400,'invalid');
   if(await env.DB.prepare('SELECT id FROM users WHERE username = ?').bind(name.value).first())return error(409,'username_taken');
   const id=crypto.randomUUID(),salt=random(16),hash=await passwordHash(x.password as string,salt);
   await env.DB.prepare('INSERT INTO users(id,username,password_hash,password_salt,kdf,wrapped_key,created_at) VALUES(?,?,?,?,?,?,?)').bind(id,name.value,hash,salt,JSON.stringify(x.kdf),JSON.stringify(x.wrappedKey),Date.now()).run();return json({ok:true},201);
  }
  if(req.method==='POST'&&p==='/api/login'){
   const x=await body(req),key=req.headers.get('CF-Connecting-IP')||'unknown';if(await rateLimited(env,key))return error(429,'rate_limited');const name=validateUsername(x.username);if(!name.valid)return error(400,'invalid_username');
   const usr=await env.DB.prepare('SELECT id,username,password_hash,password_salt,kdf,wrapped_key FROM users WHERE username = ?').bind(name.value).first<User>();
   const ok=usr&&typeof x.password==='string'&&equal(await passwordHash(x.password,usr.password_salt),usr.password_hash);
   if(!ok){await env.DB.prepare('INSERT INTO login_attempts(key,attempted_at) VALUES(?,?)').bind(key,Date.now()).run();return error(401,'invalid_credentials')}
   await env.DB.prepare('DELETE FROM login_attempts WHERE key = ?').bind(key).run();const token=random(),csrf=random(24);
   await env.DB.prepare('INSERT INTO sessions(id_hash,user_id,csrf_hash,expires_at) VALUES(?,?,?,?)').bind(await digest(token),usr.id,await digest(csrf),Date.now()+SESSION_SECONDS*1000).run();
   return json({csrf,...material(usr)},200,{'set-cookie':`${COOKIE}=${token}; HttpOnly; Secure; SameSite=Strict; Path=/; Max-Age=${SESSION_SECONDS}`});
  }
  const s=await session(req,env);if(!s)return error(401,'unauthorized');
  if(!['GET','HEAD'].includes(req.method)&&!await safe(req,s))return error(403,'csrf');
  if(req.method==='GET'&&p==='/api/session')return json({username:s.username,...material(s)});
  if(req.method==='POST'&&p==='/api/logout'){await env.DB.prepare('DELETE FROM sessions WHERE id_hash = ?').bind(s.id_hash).run();return json({ok:true},200,{'set-cookie':`${COOKIE}=; HttpOnly; Secure; SameSite=Strict; Path=/; Max-Age=0`})}
  if(req.method==='POST'&&p==='/api/change-username'){
   const x=await body(req),keys=Object.keys(x);if(keys.length!==2||!keys.includes('newUsername')||!keys.includes('currentPassword'))return error(400,'invalid_request');const name=validateUsername(x.newUsername);if(!name.valid)return error(400,'invalid_username');if(!validPassword(x.currentPassword)||!equal(await passwordHash(x.currentPassword as string,s.password_salt),s.password_hash))return error(401,'invalid_current_password');try{await env.DB.batch([env.DB.prepare('UPDATE users SET username=? WHERE id=?').bind(name.value,s.user_id),env.DB.prepare('DELETE FROM sessions WHERE user_id=?').bind(s.user_id)])}catch(e){if(String(e).includes('UNIQUE'))return error(409,'username_taken');throw e}return json({ok:true},200,{'set-cookie':`${COOKIE}=; HttpOnly; Secure; SameSite=Strict; Path=/; Max-Age=0`});
  }
  if(req.method==='POST'&&p==='/api/change-password'){
   const x=await body(req);
   if(typeof x.currentPassword!=='string'||!equal(await passwordHash(x.currentPassword,s.password_salt),s.password_hash))return error(401,'invalid_current_password');
   if(typeof x.newPassword!=='string'||x.newPassword.length<12||x.newPassword.length>1024)return error(400,'invalid_new_password');
   if(!validKey(x))return error(400,'invalid_key_material');
   const salt=random(16),hash=await passwordHash(x.newPassword,salt);
   await env.DB.batch([env.DB.prepare('UPDATE users SET password_hash=?,password_salt=?,kdf=?,wrapped_key=? WHERE id=?').bind(hash,salt,JSON.stringify(x.kdf),JSON.stringify(x.wrappedKey),s.user_id),env.DB.prepare('DELETE FROM sessions WHERE user_id = ?').bind(s.user_id)]);return json({ok:true},200,{'set-cookie':`${COOKIE}=; HttpOnly; Secure; SameSite=Strict; Path=/; Max-Age=0`});
  }
  if(req.method==='GET'&&p==='/api/entries'){const r=await env.DB.prepare('SELECT id,type,version,iv,ciphertext,created_at FROM entries WHERE user_id = ? ORDER BY updated_at DESC').bind(s.user_id).all();return json({items:r.results.map((v:any)=>({id:v.id,type:v.type,version:v.version,iv:v.iv,ciphertext:v.ciphertext,createdAt:v.created_at}))})}
  if(req.method==='GET'&&p==='/api/attachments'){const r=await env.DB.prepare('SELECT id,metadata_iv,metadata_ciphertext,ciphertext_size,created_at,updated_at FROM attachments WHERE user_id=? ORDER BY updated_at DESC').bind(s.user_id).all();return json({items:r.results.map((v:any)=>({id:v.id,metadata:{version:1,iv:v.metadata_iv,ciphertext:v.metadata_ciphertext},ciphertextSize:v.ciphertext_size,createdAt:v.created_at,updatedAt:v.updated_at}))})}
  const am=p.match(/^\/api\/attachments\/([^/]+)(?:\/(content|metadata))?$/);if(am){const id=decodeURIComponent(am[1]);if(!validAttachmentId(id))return error(400,'invalid_id');const action=am[2];
   if(req.method==='POST'&&!action){const declared=req.headers.get('content-length');if(declared===null)return error(411,'length_required');const length=Number(declared);if(!Number.isSafeInteger(length)||length<16||length>MAX_WORKER_UPLOAD||!req.body)return error(413,'too_large');let metadata:unknown;try{metadata=JSON.parse(req.headers.get('x-attachment-metadata')||'')}catch{return error(400,'invalid_metadata')}if(!validAttachmentEnvelope(metadata))return error(400,'invalid_metadata');if(await env.DB.prepare('SELECT 1 FROM attachments WHERE user_id=? AND id=?').bind(s.user_id,id).first())return error(409,'attachment_exists');const bytes=await req.arrayBuffer();if(bytes.byteLength!==length)return error(400,'invalid_content_length');await reserveStorage(env,length);let committed=false,key='';const now=Date.now();try{await reserveOperation(env,'class_a');key=`${await digest(s.user_id)}/${random(32)}`;await env.ATTACHMENTS.put(key,bytes,{httpMetadata:{contentType:'application/octet-stream'}});await env.DB.prepare('INSERT INTO attachments VALUES(?,?,?,?,?,?,?,?)').bind(s.user_id,id,(metadata as any).iv,(metadata as any).ciphertext,key,length,now,now).run();committed=true;return json({id,metadata,ciphertextSize:length,createdAt:now,updatedAt:now},201)}catch(e){if(key)try{await env.ATTACHMENTS.delete(key)}catch{}throw e}finally{if(!committed)await reserveStorage(env,-length)}}
   const row=await env.DB.prepare('SELECT * FROM attachments WHERE user_id=? AND id=?').bind(s.user_id,id).first<any>();if(!row)return error(404,'not_found');
   if(req.method==='GET'&&action==='content'){await reserveOperation(env,'class_b');const object=await env.ATTACHMENTS.get(row.object_key);if(!object)return error(404,'not_found');return new Response(object.body,{headers:{...SECURITY_HEADERS,'content-type':'application/octet-stream','content-length':String(row.ciphertext_size),'cache-control':'no-store'}})}
   if(req.method==='PUT'&&action==='metadata'){const x=await body(req);if(!validAttachmentEnvelope(x))return error(400,'invalid_metadata');const now=Date.now();await env.DB.prepare('UPDATE attachments SET metadata_iv=?,metadata_ciphertext=?,updated_at=? WHERE user_id=? AND id=?').bind(x.iv,x.ciphertext,now,s.user_id,id).run();return json({id,metadata:x,ciphertextSize:row.ciphertext_size,createdAt:row.created_at,updatedAt:now})}
   if(req.method==='DELETE'&&!action){await env.ATTACHMENTS.delete(row.object_key);await env.DB.prepare('DELETE FROM attachments WHERE user_id=? AND id=?').bind(s.user_id,id).run();await reserveStorage(env,-Number(row.ciphertext_size));return new Response(null,{status:204,headers:{...SECURITY_HEADERS,'cache-control':'no-store'}})}
  }
  if(p.startsWith('/api/entries/')){const id=decodeURIComponent(p.slice('/api/entries/'.length));if(!/^[a-zA-Z0-9_-]{8,80}$/.test(id))return error(400,'invalid_id');
   if(req.method==='PUT'){const x=envelope(await body(req),id);if(!x)return error(400,'invalid_envelope');const now=Date.now();await env.DB.prepare('INSERT INTO entries(user_id,id,type,version,iv,ciphertext,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?) ON CONFLICT(user_id,id) DO UPDATE SET type=excluded.type,version=excluded.version,iv=excluded.iv,ciphertext=excluded.ciphertext,updated_at=excluded.updated_at').bind(s.user_id,x.id,x.type,x.version,x.iv,x.ciphertext,now,now).run();const row=await env.DB.prepare('SELECT id,type,version,iv,ciphertext,created_at FROM entries WHERE user_id = ? AND id = ?').bind(s.user_id,id).first<any>();return json({...x,createdAt:row.created_at})}
   if(req.method==='DELETE'){await env.DB.prepare('DELETE FROM entries WHERE user_id = ? AND id = ?').bind(s.user_id,id).run();return new Response(null,{status:204,headers:{...SECURITY_HEADERS,'cache-control':'no-store'}})}
  }
  if(req.method==='GET'&&p==='/api/backup'){
   const er=await env.DB.prepare('SELECT id,type,version,iv,ciphertext FROM entries WHERE user_id = ? ORDER BY updated_at DESC').bind(s.user_id).all();
   if(u.searchParams.get('attachments')!=='1')return json({version:1,...material(s),envelopes:er.results});
   const stats=await env.DB.prepare('SELECT COUNT(*) AS count, COALESCE(SUM(ciphertext_size),0) AS total FROM attachments WHERE user_id=?').bind(s.user_id).first<any>();if(Number(stats?.count)>1000||Number(stats?.total)>MAX_BACKUP_ATTACHMENTS)return error(413,'backup_attachments_too_large');const ar=await env.DB.prepare('SELECT id,metadata_iv,metadata_ciphertext,object_key,ciphertext_size,created_at,updated_at FROM attachments WHERE user_id=? ORDER BY updated_at DESC').bind(s.user_id).all();const attachments=[];
   for(const row of ar.results as any[]){await reserveOperation(env,'class_b');const object=await env.ATTACHMENTS.get(row.object_key);if(!object)return error(409,'missing_attachment_object');const bytes=await new Response(object.body).arrayBuffer();if(bytes.byteLength!==row.ciphertext_size)return error(409,'attachment_size_mismatch');attachments.push({id:row.id,metadata:{version:1,iv:row.metadata_iv,ciphertext:row.metadata_ciphertext},ciphertextSize:row.ciphertext_size,createdAt:row.created_at,updatedAt:row.updated_at,sha256:await digestBytes(bytes),object:bytesToB64(bytes)})}
   return json({format:'pass-vault-v2',version:2,...material(s),entries:er.results,attachments});
  }
  if(req.method==='PUT'&&p==='/api/backup'){
   const x=await limitedJson(req,MAX_BACKUP_JSON);
   if(x.version===1){if(!validKey(x)||!Array.isArray(x.envelopes)||x.envelopes.length>10000)return error(400,'invalid_backup');const items=x.envelopes.map((v:any)=>envelope(v));if(items.some((v:any)=>!v)||new Set(items.map((v:any)=>v.id)).size!==items.length)return error(400,'invalid_backup');const now=Date.now();await env.DB.batch([env.DB.prepare('UPDATE users SET kdf=?,wrapped_key=? WHERE id=?').bind(JSON.stringify(x.kdf),JSON.stringify(x.wrappedKey),s.user_id),env.DB.prepare('DELETE FROM entries WHERE user_id = ?').bind(s.user_id),...items.map((v:any)=>env.DB.prepare('INSERT INTO entries(user_id,id,type,version,iv,ciphertext,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?)').bind(s.user_id,v.id,v.type,v.version,v.iv,v.ciphertext,now,now))]);return json({ok:true,count:items.length,attachments:0})}
   if(x.version!==2||x.format!=='pass-vault-v2'||!validKey(x)||!Array.isArray(x.entries)||!Array.isArray(x.attachments)||x.entries.length>10000||x.attachments.length>1000)return error(400,'invalid_backup');const entries=x.entries.map((v:any)=>envelope(v));if(entries.some((v:any)=>!v)||new Set(entries.map((v:any)=>v.id)).size!==entries.length)return error(400,'invalid_backup');const ids=new Set<string>(),prepared=[];let total=0;
   for(const a of x.attachments){if(!a||ids.has(a.id)||!validAttachmentId(a.id)||!validAttachmentEnvelope(a.metadata)||!Number.isSafeInteger(a.ciphertextSize)||a.ciphertextSize<16||a.ciphertextSize>MAX_WORKER_UPLOAD||typeof a.object!=='string'||typeof a.sha256!=='string')return error(400,'invalid_backup');ids.add(a.id);const bytes=b64ToBytes(a.object);if(!bytes||bytes.byteLength!==a.ciphertextSize||await digestBytes(bytes.buffer)!==a.sha256)return error(400,'invalid_backup');total+=bytes.byteLength;if(total>MAX_BACKUP_ATTACHMENTS)return error(413,'too_large');prepared.push({...a,bytes,key:`${await digest(s.user_id)}/${random(32)}`})}
   const old=(await env.DB.prepare('SELECT id,metadata_iv,metadata_ciphertext,object_key,ciphertext_size,created_at,updated_at FROM attachments WHERE user_id=? ORDER BY updated_at DESC').bind(s.user_id).all()).results as any[],oldTotal=(old as any[]).reduce((n,row)=>n+Number(row.ciphertext_size),0),uploaded:string[]=[],delta=total-oldTotal;await reserveStorage(env,delta);let committed=false;try{for(const a of prepared){await reserveOperation(env,'class_a');await env.ATTACHMENTS.put(a.key,a.bytes,{httpMetadata:{contentType:'application/octet-stream'}});uploaded.push(a.key)}const now=Date.now();await env.DB.batch([env.DB.prepare('UPDATE users SET kdf=?,wrapped_key=? WHERE id=?').bind(JSON.stringify(x.kdf),JSON.stringify(x.wrappedKey),s.user_id),env.DB.prepare('DELETE FROM entries WHERE user_id = ?').bind(s.user_id),env.DB.prepare('DELETE FROM attachments WHERE user_id = ?').bind(s.user_id),...entries.map((v:any)=>env.DB.prepare('INSERT INTO entries(user_id,id,type,version,iv,ciphertext,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?)').bind(s.user_id,v.id,v.type,v.version,v.iv,v.ciphertext,now,now)),...prepared.map(a=>env.DB.prepare('INSERT INTO attachments VALUES(?,?,?,?,?,?,?,?)').bind(s.user_id,a.id,a.metadata.iv,a.metadata.ciphertext,a.key,a.ciphertextSize,a.createdAt||now,a.updatedAt||now))]);committed=true}catch(e){for(const key of uploaded)try{await env.ATTACHMENTS.delete(key)}catch{}throw e}finally{if(!committed)await reserveStorage(env,-delta)}for(const row of old){try{await env.ATTACHMENTS.delete(row.object_key)}catch(e){console.error(JSON.stringify({event:'attachment_cleanup_failed'}))}}return json({ok:true,count:entries.length,attachments:prepared.length})
  }
  return error(404,'not_found');
 }catch(e){if(e instanceof QuotaExceeded)return json({error:'quota_exceeded',quota:e.quota},429);if(e instanceof SyntaxError)return error(400,'invalid_json');if(e instanceof RangeError)return error(413,'too_large');console.error(JSON.stringify({event:'request_error',message:e instanceof Error?e.message:'unknown'}));return error(500,'internal_error')}
}} satisfies ExportedHandler<Env>;
