import test from 'node:test';
import assert from 'node:assert/strict';
import { chromium, webkit } from 'playwright';
import { spawn } from 'node:child_process';
import { rm } from 'node:fs/promises';
import { fillTestInvite, withTestInviteEnv } from './fixtures.mjs';

const port=4396,base=`http://127.0.0.1:${port}`,db=`/tmp/pass-vault-scroll-${process.pid}.sqlite`;
let server;
test.before(async()=>{await rm(db,{force:true});server=spawn(process.execPath,['apps/server/server.mjs'],{env:{...withTestInviteEnv(),PORT:String(port),DB_PATH:db,COOKIE_SECURE:'false'},stdio:['ignore','ignore','pipe']});for(let i=0;i<80;i++){try{if((await fetch(base)).ok)return}catch{}await new Promise(r=>setTimeout(r,100))}throw Error('server timeout')});
test.after(async()=>{if(server?.exitCode===null){server.kill('SIGTERM');await new Promise(r=>server.once('exit',r))}await rm(db,{force:true})});
async function register(page,label){await page.goto(base);await page.getByRole('button',{name:'创建新库'}).click();await fillTestInvite(page);await page.getByLabel('用户名').fill(`scroll-${label}-${Date.now()}-${Math.random()}`);await page.getByLabel('主密码',{exact:true}).fill('correct horse battery staple');await page.getByRole('button',{name:'创建并进入'}).click();await page.locator('#vault').waitFor({state:'visible'});await page.getByRole('button',{name:'+ 新建'}).click();await page.locator('#picker').getByRole('button',{name:'笔记',exact:true}).click();const editor=page.locator('#editor');await editor.getByLabel('标题').fill('Scroll seed');await editor.getByLabel('正文').fill('detail '.repeat(500));await editor.getByRole('button',{name:'保存'}).click();await page.locator('.item-card').waitFor();await page.evaluate(()=>{const list=document.querySelector('#list'),seed=list.querySelector('.item-card');for(let i=1;i<45;i++){const copy=seed.cloneNode(true);copy.querySelector('b').textContent=`Scroll item ${i}`;list.append(copy)}})}
const rects=page=>page.evaluate(()=>{const box=s=>{const r=document.querySelector(s).getBoundingClientRect();return{x:r.x,y:r.y,width:r.width,height:r.height,bottom:r.bottom,right:r.right}};return{header:box('header'),nav:box('nav'),toolbar:box('.toolbar'),detail:box('#detail')}});
async function assertChromeStill(page,before){const after=await rects(page);assert.deepEqual(after,before);assert.deepEqual(await page.evaluate(()=>({window:scrollY,body:document.body.scrollTop,root:document.documentElement.scrollTop})),{window:0,body:0,root:0});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>document.documentElement.clientWidth),false)}
for(const [name,launcher] of [['chromium',chromium],['webkit',webkit]])for(const width of [320,390,1280])test(`${name} ${width}: app chrome stays put while list and detail scroll independently`,async()=>{const browser=await launcher.launch({headless:true}),page=await browser.newPage({viewport:{width,height:800}});try{await register(page,`${name}-${width}`);const list=page.locator('#list'),before=await rects(page);await list.hover();await page.mouse.wheel(0,650);await page.waitForTimeout(100);assert.ok(await list.evaluate(e=>e.scrollTop)>0,'list.scrollTop must increase');await assertChromeStill(page,before);await list.evaluate(e=>{e.scrollTop=e.scrollHeight});assert.ok(await list.evaluate(e=>e.lastElementChild.getBoundingClientRect().bottom<=e.getBoundingClientRect().bottom+1),'last item must be reachable');await page.locator('.item-card').first().click();await page.locator('#detail.open').waitFor();await page.waitForTimeout(300);const detailBefore=await rects(page);await page.locator('#detail').hover();await page.mouse.wheel(0,650);await page.waitForTimeout(100);assert.ok(await page.locator('#detail').evaluate(e=>e.scrollTop)>0,'detail.scrollTop must increase');await assertChromeStill(page,detailBefore)}finally{await browser.close()}});
