import test from 'node:test';
import assert from 'node:assert/strict';
import { chromium, webkit, devices } from 'playwright';
import { spawn } from 'node:child_process';
import { rm } from 'node:fs/promises';

const port=4333,base=`http://localhost:${port}`,db=`/tmp/pass-vault-auth-entrance-${process.pid}.sqlite`;
let server;
test.before(async()=>{server=spawn(process.execPath,['apps/server/server.mjs'],{env:{...process.env,PORT:String(port),DB_PATH:db,ATTACHMENTS_DIR:`/tmp/pass-vault-auth-entrance-${process.pid}-files`,COOKIE_SECURE:'false'}});for(let i=0;i<120;i++){try{if((await fetch(base)).ok)return}catch{}await new Promise(r=>setTimeout(r,50))}throw Error('server timeout')});
test.after(async()=>{if(server?.exitCode===null){server.kill('SIGTERM');await new Promise(r=>server.once('exit',r))}await rm(db,{force:true});await rm(`${db}-shm`,{force:true});await rm(`${db}-wal`,{force:true});await rm(`/tmp/pass-vault-auth-entrance-${process.pid}-files`,{recursive:true,force:true})});

const sample=()=>{const shell=document.querySelector('#auth'),el=document.querySelector('#auth-form'),style=getComputedStyle(el),box=shell.getBoundingClientRect();return{opacity:Number(style.opacity),transform:style.transform,animationName:style.animationName,box:[box.x,box.y,box.width,box.height],starts:window.__authStarts||0}};
async function run(browser,options,reducedMotion){const context=await browser.newContext({...options,reducedMotion});await context.addInitScript(()=>{window.__authStarts=0;addEventListener('animationstart',event=>{if(event.animationName==='auth-in')window.__authStarts++},true)});const page=await context.newPage();await page.goto(base,{waitUntil:'domcontentloaded'});const samples=await page.evaluate(async source=>{const get=(0,eval)(`(${source})`),out=[{ms:'same-frame',...get()}],started=performance.now();for(const ms of [0,16,50,120,180,240]){const wait=started+ms-performance.now();if(wait>0)await new Promise(r=>setTimeout(r,wait));out.push({ms,...get()})}return out},sample.toString());
 const boxes=samples.map(x=>x.box);assert.ok(boxes.every(x=>JSON.stringify(x)===JSON.stringify(boxes[0])),'auth entrance shifted layout');
 if(reducedMotion==='reduce'){assert.ok(samples.every(x=>x.opacity===1&&x.transform==='none'&&x.animationName==='none'&&x.starts===0),JSON.stringify(samples))}
 else {assert.ok(samples.some(x=>x.animationName==='auth-in'&&x.opacity<1),'no post-paint auth entrance');assert.ok(samples.every(x=>x.starts<=1),'auth entrance replayed');assert.ok(samples.at(-1).opacity>.99,JSON.stringify(samples));await page.waitForFunction(()=>!document.querySelector('#auth').classList.contains('auth-initial'));const settled=await page.evaluate(sample);assert.equal(settled.opacity,1);assert.equal(settled.transform,'none');assert.equal(settled.animationName,'none');assert.equal(settled.starts,1);await page.getByRole('button',{name:'创建新库'}).click();await page.getByRole('button',{name:'返回登录'}).click();await page.getByRole('button',{name:'登录并解锁'}).click();await page.waitForTimeout(50);assert.equal((await page.evaluate(sample)).starts,1)}
 await context.close()}

test('initial auth enters exactly once after first paint without layout shift or reduced-motion delay',async()=>{for(const [launcher,cases] of [[chromium,[{viewport:{width:1280,height:800}},{viewport:{width:390,height:844}}]],[webkit,[{viewport:{width:1280,height:800}},{...devices['iPhone 13']}]]]){const browser=await launcher.launch({headless:true});try{for(const options of cases)for(const motion of ['no-preference','reduce'])await run(browser,options,motion)}finally{await browser.close()}}});