import test from 'node:test';
import assert from 'node:assert/strict';
import { chromium, webkit } from 'playwright';
import { spawn } from 'node:child_process';

const port=4389,base=`http://127.0.0.1:${port}`;let server;
test.before(async()=>{server=spawn(process.execPath,['apps/server/server.mjs'],{env:{...process.env,PORT:String(port),DB_PATH:`/tmp/custom-groups-${process.pid}.sqlite`,COOKIE_SECURE:'false'}});for(let i=0;i<60;i++){try{if((await fetch(base)).ok)return}catch{}await new Promise(r=>setTimeout(r,100))}throw Error('server timeout')});
test.after(async()=>{if(server?.exitCode===null){server.kill();await new Promise(r=>server.once('exit',r))}});
async function register(page){const user=`groups-${Date.now()}-${Math.random()}`;await page.goto(base);await page.getByRole('button',{name:'创建新库'}).click();await page.getByLabel('用户名').fill(user);await page.getByLabel('主密码',{exact:true}).fill('correct horse battery staple');await page.getByRole('button',{name:'创建并进入'}).click();await page.locator('#vault').waitFor({state:'visible'});return user}
async function createGroup(page,name){await page.getByRole('button',{name:/管理.*分组/}).click();const d=page.getByRole('dialog',{name:'分组',exact:true});await d.getByLabel('新分组名称').fill(name);await d.getByRole('button',{name:'创建分组'}).click();await d.getByRole('button',{name:'关闭'}).click()}
for(const engine of [chromium,webkit])test(`${engine.name()} 空分组持久化、分类独立、加密且移动端无溢出`,async()=>{const browser=await engine.launch({headless:true}),page=await browser.newPage({viewport:{width:320,height:800}});try{const bodies=[];page.on('request',r=>{if(r.method()==='PUT')bodies.push(r.postData()||r.headers()['x-attachment-metadata']||'')});const user=await register(page);await createGroup(page,'工作机密');await page.reload();await page.getByLabel('用户名').fill(user||'');await page.getByLabel('主密码',{exact:true}).fill('correct horse battery staple');await page.getByRole('button',{name:'登录并解锁'}).click();await page.locator('#vault').waitFor({state:'visible'});await page.getByRole('button',{name:/管理账号分组/}).click();assert.match(await page.getByRole('dialog',{name:/分组/}).textContent(),/工作机密/);await page.getByRole('dialog',{name:/分组/}).getByRole('button',{name:'关闭'}).click();await page.locator('nav').getByRole('button',{name:'网站'}).click();assert.match(await page.getByRole('button',{name:/管理网站分组/}).textContent(),/默认/);assert.equal(bodies.some(x=>x.includes('工作机密')),false);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>document.documentElement.clientWidth),false)}finally{await browser.close()}});
test('创建、分配、搜索、重命名和删除回默认',async()=>{const browser=await chromium.launch({headless:true}),page=await browser.newPage();try{await register(page);await page.locator('nav').getByRole('button',{name:'笔记'}).click();await createGroup(page,'工作');await page.getByRole('button',{name:'+ 新建'}).click();await page.locator('#picker').getByRole('button',{name:'笔记'}).click();const e=page.locator('#editor');await e.getByLabel('标题').fill('Alpha秘密');await e.getByLabel('正文').fill('正文');await e.getByLabel('分组').selectOption({label:'工作'});await e.getByRole('button',{name:'保存'}).click();await page.getByPlaceholder('搜索当前分类').fill('Alpha');assert.equal(await page.locator('.item-card').count(),1);await page.getByRole('button',{name:/管理笔记分组/}).click();const d=page.getByRole('dialog',{name:'分组',exact:true});await d.getByRole('button',{name:'重命名 工作'}).click();await page.getByRole('dialog',{name:'重命名分组'}).getByLabel('分组名称',{exact:true}).fill('项目');await page.getByRole('dialog',{name:'重命名分组'}).getByRole('button',{name:'保存名称'}).click();await d.getByRole('button',{name:'删除 项目'}).waitFor();await d.getByRole('button',{name:'删除 项目'}).click();await page.getByRole('dialog',{name:'确认删除分组'}).getByRole('button',{name:'确认删除'}).click();await page.getByText('分组已删除，资料已移至默认',{exact:true}).waitFor();assert.match(await page.getByRole('button',{name:/管理笔记分组/}).textContent(),/默认/)}finally{await browser.close()}});

test('附件分组上传、类别过滤、移动、刷新及删除回默认均加密',async()=>{const browser=await chromium.launch({headless:true}),page=await browser.newPage();try{const bodies=[];page.on('request',r=>{if(['POST','PUT'].includes(r.method()))bodies.push(`${r.postData()||''}${r.headers()['x-attachment-metadata']||''}`)});const user=await register(page);await page.locator('nav').getByRole('button',{name:'附件'}).click();await createGroup(page,'附件机密');await page.getByRole('button',{name:'+ 新建'}).click();await page.locator('#picker').getByRole('button',{name:'附件'}).click();const upload=page.getByRole('dialog',{name:'上传附件'});await upload.getByLabel('分组').selectOption({label:'附件机密'});await upload.getByLabel('选择文件').setInputFiles({name:'proof.txt',mimeType:'text/plain',buffer:Buffer.from('secret')});await upload.getByRole('button',{name:'加密并上传'}).click();await page.getByRole('button',{name:'proof.txt'}).waitFor();await page.getByLabel('附件分类').selectOption('image');assert.equal(await page.getByRole('button',{name:'proof.txt'}).count(),0);await page.getByLabel('附件分类').selectOption('other');await page.getByRole('button',{name:'proof.txt'}).click();await page.getByRole('button',{name:'重命名'}).click();const rename=page.getByRole('dialog',{name:'重命名附件'});await rename.getByLabel('分组').selectOption('');await rename.getByRole('button',{name:'保存'}).click();await page.reload();await page.getByLabel('用户名').fill(user);await page.getByLabel('主密码',{exact:true}).fill('correct horse battery staple');await page.getByRole('button',{name:'登录并解锁'}).click();await page.locator('#vault').waitFor({state:'visible'});await page.locator('nav').getByRole('button',{name:'附件'}).click();await page.getByRole('button',{name:/管理附件分组/}).click();const d=page.getByRole('dialog',{name:'分组',exact:true});await d.getByRole('button',{name:'删除 附件机密'}).click();await page.getByRole('dialog',{name:'确认删除分组'}).getByRole('button',{name:'确认删除'}).click();await page.getByText('分组已删除，资料已移至默认',{exact:true}).waitFor();assert.equal(bodies.some(x=>x.includes('附件机密')||x.includes('groupId')),false)}finally{await browser.close()}});

test('分组名称约束与创建失败回滚',async()=>{const browser=await chromium.launch({headless:true}),page=await browser.newPage();try{await register(page);await page.locator('nav').getByRole('button',{name:'笔记'}).click();await page.getByRole('button',{name:/管理笔记分组/}).click();const d=page.getByRole('dialog',{name:'分组',exact:true}),input=d.getByLabel('新分组名称');for(const bad of ['bad\u200bname','x'.repeat(41)]){await input.fill(bad);await d.getByRole('button',{name:'创建分组'}).click();await page.getByText('分组名称无效或重复',{exact:true}).waitFor()}await input.fill('Work');await d.getByRole('button',{name:'创建分组'}).click();await input.fill('work');await d.getByRole('button',{name:'创建分组'}).click();await d.getByRole('button',{name:'Work（0）',exact:true}).click();let failed=false;await page.route('**/api/entries/settings_registry',async route=>{if(!failed&&route.request().method()==='PUT'){failed=true;await route.fulfill({status:500,contentType:'application/json',body:'{"error":"internal_error"}'})}else await route.continue()});await input.fill('Rollback');await d.getByRole('button',{name:'创建分组'}).click();await d.getByRole('button',{name:'Work（0）',exact:true}).waitFor();assert.equal(failed,true);assert.equal(await d.getByRole('button',{name:/Rollback/}).count(),0);assert.equal(await d.getByRole('button',{name:'Work（0）',exact:true}).count(),1)}finally{await browser.close()}});

test('删除分组第二条笔记写入失败后补偿并在重新登录后恢复服务器密文',async()=>{const browser=await chromium.launch({headless:true}),page=await browser.newPage();try{
 const user=await register(page);await page.locator('nav').getByRole('button',{name:'笔记'}).click();await createGroup(page,'补偿组');
 for(const title of ['补偿一','补偿二']){await page.getByRole('button',{name:'+ 新建'}).click();await page.locator('#picker').getByRole('button',{name:'笔记'}).click();const editor=page.locator('#editor');await editor.getByLabel('标题').fill(title);await editor.getByLabel('正文').fill(`${title}正文`);await editor.getByLabel('分组').selectOption({label:'补偿组'});await editor.getByRole('button',{name:'保存'}).click();await page.locator('.item-card').filter({hasText:title}).waitFor()}
 let deletionPuts=0,resolveFailure;const failureSeen=new Promise(resolve=>{resolveFailure=resolve});await page.route('**/api/entries/**',async route=>{const request=route.request(),url=new URL(request.url());if(request.method()==='PUT'&&url.pathname!='/api/entries/settings_registry'){deletionPuts++;if(deletionPuts===2){resolveFailure();return route.fulfill({status:500,contentType:'application/json',body:'{"error":"internal_error"}'})}}await route.continue()});
 await page.getByRole('button',{name:/管理笔记分组/}).click();const groups=page.getByRole('dialog',{name:'分组',exact:true});await groups.getByRole('button',{name:'删除 补偿组'}).click();await page.getByRole('dialog',{name:'确认删除分组'}).getByRole('button',{name:'确认删除'}).click();
 await failureSeen;await groups.getByRole('button',{name:'补偿组（2）',exact:true}).waitFor();assert.equal(deletionPuts,3);assert.match(await page.getByRole('button',{name:/管理笔记分组/}).textContent(),/补偿组/);assert.equal(await groups.getByRole('button',{name:'补偿组（2）',exact:true}).count(),1);
 await page.reload();await page.getByLabel('用户名').fill(user);await page.getByLabel('主密码',{exact:true}).fill('correct horse battery staple');await page.getByRole('button',{name:'登录并解锁'}).click();await page.locator('#vault').waitFor({state:'visible'});await page.locator('nav').getByRole('button',{name:'笔记'}).click();assert.equal(await page.getByRole('button',{name:'补偿一'}).count(),0);assert.equal(await page.getByRole('button',{name:'补偿二'}).count(),0);
 await page.getByRole('button',{name:/管理笔记分组/}).click();const reloadedGroups=page.getByRole('dialog',{name:'分组',exact:true});await reloadedGroups.getByRole('button',{name:'补偿组（2）',exact:true}).click();await reloadedGroups.getByRole('button',{name:'关闭'}).click();await page.locator('.item-card').filter({hasText:'补偿一'}).waitFor();await page.locator('.item-card').filter({hasText:'补偿二'}).waitFor();assert.equal(await page.locator('.item-card').count(),2);
 }finally{await browser.close()}});
