import test from 'node:test';
import assert from 'node:assert/strict';
import { chromium, webkit, devices } from 'playwright';
import { spawn } from 'node:child_process';
import { rm, mkdir, writeFile } from 'node:fs/promises';

const port=4332,base=`http://localhost:${port}`,db=`/tmp/pass-vault-login-${process.pid}.sqlite`,password='correct horse battery staple';
let server;
async function start(){server=spawn(process.execPath,['apps/server/server.mjs'],{env:{...process.env,PORT:String(port),DB_PATH:db,COOKIE_SECURE:'false'}});await new Promise((resolve,reject)=>{const end=Date.now()+6000;(async function ping(){try{if((await fetch(base)).ok)return resolve()}catch{}if(Date.now()>end)return reject(Error('server timeout'));setTimeout(ping,50)})()})}
async function stop(){if(server?.exitCode===null){server.kill('SIGTERM');await new Promise(r=>server.once('exit',r))}await rm(db,{force:true})}
test.before(async()=>{await mkdir('artifacts/login-stability',{recursive:true});await start()});test.after(stop);
async function create(page,i){await page.getByRole('button',{name:'+ 新建'}).click();await page.locator('#picker').getByRole('button',{name:'账号',exact:true}).click();const e=page.locator('#editor');for(const [n,v] of Object.entries({'平台':`LOGIN-${String(i).padStart(2,'0')}`,'登录网址':`https://login-${i}.example`,'账号':`user-${i}`,'密码':`secret-${i}`,'备注':'login stability fixture','标签（逗号分隔）':'test'}))await e.getByLabel(n,{exact:true}).fill(v);await e.getByRole('button',{name:'保存'}).click();await page.getByText('已保存',{exact:true}).waitFor()}
async function seed(browser,username){const page=await browser.newPage({viewport:{width:390,height:844},reducedMotion:'reduce'});await page.goto(base);await page.getByRole('button',{name:'创建新库'}).click();await page.getByLabel('用户名').fill(username);await page.getByLabel('主密码',{exact:true}).fill(password);await page.getByRole('button',{name:'创建并进入'}).click();await page.locator('#vault').waitFor({state:'visible'});for(let i=1;i<=12;i++)await create(page,i);await page.getByRole('button',{name:'更多',exact:true}).click();await page.getByRole('menuitem',{name:'退出'}).click();await page.locator('#auth').waitFor({state:'visible'});await page.close()}
const probe=()=>{const pick=el=>{const s=getComputedStyle(el),r=el.getBoundingClientRect();return{hidden:el.hidden,top:r.top,left:r.left,width:r.width,height:r.height,opacity:s.opacity,transform:s.transform,animationName:s.animationName}};const cards=[...document.querySelectorAll('#list .item-card')];return{auth:pick(document.querySelector('#auth')),vault:pick(document.querySelector('#vault')),list:{...pick(document.querySelector('#list')),childCount:document.querySelector('#list').children.length},cards:cards.map((x,i)=>({i,text:x.querySelector('b')?.textContent,...pick(x),identity:x.dataset.loginIdentity})),scroll:{x:scrollX,y:scrollY},shifts:window.__loginShifts||[],mutations:window.__loginMutations||0,revealStarts:window.__vaultRevealStarts||0}}
async function runCase(browser,contextOptions,label,username,reducedMotion){const context=await browser.newContext({...contextOptions,reducedMotion});await context.addInitScript(()=>{window.__loginMutations=0;window.__loginShifts=[];window.__vaultRevealStarts=0;addEventListener('animationstart',event=>{if(event.animationName==='vault-reveal')window.__vaultRevealStarts++},true);new PerformanceObserver(list=>window.__loginShifts.push(...list.getEntries().filter(x=>!x.hadRecentInput).map(x=>({value:x.value,time:x.startTime})))).observe({type:'layout-shift',buffered:true});addEventListener('DOMContentLoaded',()=>new MutationObserver(ms=>{for(const m of ms)if(m.target.id==='list'||m.target.closest?.('#list'))window.__loginMutations++}).observe(document.documentElement,{childList:true,subtree:true}))});const page=await context.newPage(),errors=[];page.on('console',m=>{if(['error','warning'].includes(m.type()))errors.push(`${m.type()}:${m.text()}`)});page.on('pageerror',e=>errors.push(e.message));await page.goto(base);await page.getByLabel('用户名').fill(username);await page.getByLabel('主密码',{exact:true}).fill(password);const samples=await page.evaluate(async({probe})=>{const get=(0,eval)(`(${probe})`),form=document.querySelector('#auth-form'),out=[];form.requestSubmit();out.push({ms:'same-frame',...get()});let prior=0;for(const ms of [0,16,50,120,180,240,400,600,900,1300,1800,2400,3200]){if(ms>prior)await new Promise(r=>setTimeout(r,ms-prior));prior=ms;out.push({ms,...get()})}return out},{probe:probe.toString()});await writeFile(`artifacts/login-stability/${label}-${reducedMotion}.json`,JSON.stringify({label,reducedMotion,samples,errors},null,2));const revealed=samples.filter(x=>!x.vault.hidden);assert.ok(revealed.length,'vault never revealed');const first=revealed[0];if(reducedMotion==='no-preference'){assert.equal(revealed.at(-1).revealStarts,1,'normal motion must run exactly one vault reveal');}else{assert.ok(revealed.every(x=>x.vault.opacity==='1'&&x.vault.animationName==='none'&&x.revealStarts===0),'reduced motion must reveal instantly')};assert.ok(revealed.every(x=>x.vault.transform==='none'),JSON.stringify(samples));assert.ok(revealed.every(x=>x.list.childCount===12&&x.cards.every(c=>c.opacity==='1'&&c.transform==='none'&&c.animationName==='none')),JSON.stringify(samples));assert.ok(revealed.every(x=>x.mutations===first.mutations),'cards recreated after reveal');assert.deepEqual(revealed.map(x=>x.cards.map(c=>c.identity)),revealed.map(()=>first.cards.map(c=>c.identity)),'card identity changed after reveal');assert.ok(revealed.every(x=>x.shifts.length===0),'login caused a layout shift');assert.deepEqual(errors,[]);await context.close()}
test('login commits one stable vault reveal without recreating or translating cards',async()=>{const seedBrowser=await chromium.launch({headless:true}),username=`login-${Date.now()}-${Math.random()}`;try{await seed(seedBrowser,username)}finally{await seedBrowser.close()}for(const [label,launcher,options] of [['chromium-390',chromium,{viewport:{width:390,height:844}}],['webkit-iphone',webkit,{...devices['iPhone 13']}]] ){const browser=await launcher.launch({headless:true});try{for(const motion of ['no-preference','reduce'])await runCase(browser,options,label,username,motion)}finally{await browser.close()}}});
