import test from 'node:test';
import assert from 'node:assert/strict';
import { chromium, webkit } from 'playwright';
import { spawn } from 'node:child_process';
import { mkdir, writeFile } from 'node:fs/promises';
import { fillTestInvite, withTestInviteEnv } from './fixtures.mjs';

const port=4321, base=`http://localhost:${port}`,dbPath=`/tmp/pass-vault-nav-${process.pid}.sqlite`;
let server, registrations=0;
async function startServer(){server=spawn(process.execPath,['apps/server/server.mjs'],{env:{...withTestInviteEnv(),PORT:String(port),DB_PATH:dbPath,COOKIE_SECURE:'false'}});await new Promise((resolve,reject)=>{const end=Date.now()+6000;(async function ping(){try{if((await fetch(base)).ok)return resolve()}catch{}if(Date.now()>end)return reject(Error('server timeout'));setTimeout(ping,60)})()})}
async function stopServer(){if(server?.exitCode===null){server.kill('SIGTERM');await new Promise(r=>server.once('exit',r))}}
test.before(async()=>{await mkdir('artifacts/mobile-nav-flicker',{recursive:true});await startServer()});
test.after(stopServer);

async function register(page){if(registrations>=9){await stopServer();await startServer();registrations=0}registrations++;await page.goto(base);await page.getByRole('button',{name:'创建新库'}).click();await fillTestInvite(page);await page.getByLabel('用户名').fill(`nav-${Date.now()}-${Math.random()}`);await page.getByLabel('主密码',{exact:true}).fill('correct horse battery staple');await page.getByRole('button',{name:'创建并进入'}).click();await page.locator('#vault').waitFor({state:'visible'});}
async function create(page,label,values){await page.getByRole('button',{name:'+ 新建'}).click();await page.locator('#picker').getByRole('button',{name:label,exact:true}).click();const editor=page.locator('#editor'),fields={...values};if(label==='账号'){await editor.locator('input[name=credentialUsername]').fill(fields['账号']??'');await editor.locator('input[name=credentialPassword]').fill(fields['密码']??'');delete fields['账号'];delete fields['密码']}for(const [name,value] of Object.entries(fields))await editor.getByLabel(name,{exact:true}).fill(value);await editor.getByRole('button',{name:'保存'}).click();}
async function seed(page){await create(page,'账号',{'平台':'ACCOUNT-OLD','登录网址':'https://a.example','账号':'alice','密码':'secret','备注':'old detail','标签（逗号分隔）':''});await create(page,'网站',{'名称':'WEBSITE-ONLY','网址':'https://w.example','说明':'site','标签（逗号分隔）':''});await create(page,'笔记',{'标题':'NOTE-ONLY','正文':'note body','标签（逗号分隔）':''});await page.getByRole('button',{name:'+ 新建'}).click();await page.locator('#picker').getByRole('button',{name:'附件',exact:true}).click();await page.locator('#attachment-upload input[type=file]').setInputFiles({name:'ATTACHMENT-ONLY.txt',mimeType:'text/plain',buffer:Buffer.from('attachment')});await page.locator('#attachment-upload').getByRole('button',{name:'加密并上传'}).click();await page.getByText('附件已上传',{exact:true}).waitFor();}
const state=()=>{const d=document.querySelector('#detail'),l=document.querySelector('#list'),f=document.querySelector('#attachment-filter');return{detailClass:d.className,detailDisplay:getComputedStyle(d).display,detailPointer:getComputedStyle(d).pointerEvents,oldText:d.textContent.includes('ACCOUNT-OLD'),listOpacity:getComputedStyle(l).opacity,cardOpacities:[...l.querySelectorAll('.item-card')].map(x=>getComputedStyle(x).opacity),active:document.querySelector('[data-type][aria-current="page"]')?.dataset.type,filterHidden:f?.hidden??null,list:l.textContent.trim()}};

test('WebKit attachment first render never makes a visible card translucent',async()=>{const browser=await webkit.launch({headless:true});const page=await browser.newPage({viewport:{width:390,height:800},reducedMotion:'no-preference'});try{await register(page);await page.getByRole('button',{name:'+ 新建'}).click();await page.locator('#picker').getByRole('button',{name:'附件',exact:true}).click();await page.locator('#attachment-upload input[type=file]').setInputFiles({name:'FIRST-ATTACHMENT.txt',mimeType:'text/plain',buffer:Buffer.from('attachment')});await page.locator('#attachment-upload').getByRole('button',{name:'加密并上传'}).click();await page.getByText('附件已上传',{exact:true}).waitFor();const samples=[];for(const ms of [0,16,50,120,180,240]){if(ms)await page.waitForTimeout(ms-(samples.at(-1)?.ms||0));samples.push({ms,...await page.locator('.item-card',{hasText:'FIRST-ATTACHMENT.txt'}).evaluate(card=>{const style=getComputedStyle(card);return{opacity:style.opacity,animationName:style.animationName,animationDelay:style.animationDelay,className:card.className}})})}assert.ok(samples.every(sample=>sample.opacity==='1'&&sample.animationName==='none'),JSON.stringify(samples))}finally{await page.close();await browser.close()}});

for(const engine of [{name:'chromium',launch:chromium},{name:'webkit',launch:webkit}])for(const width of [320,390,768])for(const reducedMotion of ['no-preference','reduce'])test(`${engine.name} ${width} ${reducedMotion}: menu switch lifecycle and visual stability`,async()=>{const browser=await engine.launch.launch({headless:true});const context=await browser.newContext({viewport:{width,height:800},reducedMotion,recordVideo:{dir:'artifacts/mobile-nav-flicker/videos',size:{width,height:800}}});const page=await context.newPage();try{await register(page);await seed(page);await page.locator('nav').getByRole('button',{name:'账号',exact:true}).click();await page.locator('.item-card',{hasText:'ACCOUNT-OLD'}).click();await page.locator('#detail').waitFor({state:'visible'});await page.screenshot({path:`artifacts/mobile-nav-flicker/before-${engine.name}-${width}-${reducedMotion}.png`});
 const initial=await page.evaluate(()=>[...document.querySelectorAll('.item-card')].map(card=>({opacity:getComputedStyle(card).opacity,animationDelay:getComputedStyle(card).animationDelay,animationName:getComputedStyle(card).animationName})));
 assert.ok(initial.every(x=>x.opacity==='1'),'entrance cards must remain fully opaque, including animation-delay');
 const sameFrame=await page.evaluate(state=>{document.querySelector('[data-type="website"]').click();return (0,eval)(`(${state})`)()},state.toString());
 await page.screenshot({path:`artifacts/mobile-nav-flicker/after-${engine.name}-${width}-${reducedMotion}.png`});
 assert.equal(sameFrame.oldText,false,'old detail text must be removed synchronously');assert.equal(sameFrame.detailDisplay,width<=650?'none':'block','old mobile detail must not cover/intercept in click frame');assert.equal(sameFrame.active,'website');assert.match(sameFrame.list,/WEBSITE-ONLY/);assert.ok(sameFrame.cardOpacities.every(x=>x==='1'),'category list cards must stay fully opaque');assert.equal(sameFrame.filterHidden,true,'attachment filter must hide outside attachment category');
 const switched=await page.evaluate(()=>[...document.querySelectorAll('.item-card')].map(card=>getComputedStyle(card).animationName));assert.ok(switched.every(x=>x==='none'),'render(false) must disable category-switch entrance animation');
 const samples=[];for(const ms of [16,50,120,180,240]){await page.waitForTimeout(ms-(samples.at(-1)?.ms||0));samples.push({ms,...await page.evaluate(state=>(0,eval)(`(${state})`)(),state.toString())})}for(const sample of samples){assert.equal(sample.oldText,false,`old detail absent at ${sample.ms}ms`);assert.equal(sample.detailDisplay,width<=650?'none':'block');assert.ok(sample.cardOpacities.every(x=>x==='1'));assert.equal(sample.active,'website');assert.equal(sample.filterHidden,true)}
 for(const type of ['note','attachment','account','website'])await page.locator(`nav [data-type="${type}"]`).click();const final=await page.evaluate(state=>(0,eval)(`(${state})`)(),state.toString());assert.equal(final.active,'website');assert.match(final.list,/WEBSITE-ONLY/);assert.doesNotMatch(final.list,/ACCOUNT-OLD|NOTE-ONLY|ATTACHMENT-ONLY/);assert.ok(final.cardOpacities.every(x=>x==='1'));
 await page.locator('nav [data-type="attachment"]').click();assert.equal(await page.locator('#attachment-filter').isVisible(),true);await page.locator('nav [data-type="note"]').click();assert.equal(await page.locator('#attachment-filter').isVisible(),false);
 }finally{await page.close();await context.close();await browser.close()}});

test('320/390/768 and reduced motion keep synchronous category state',async()=>{const browser=await chromium.launch({headless:true});try{for(const width of [320,390,768])for(const reducedMotion of ['no-preference','reduce']){const page=await browser.newPage({viewport:{width,height:800},reducedMotion});await register(page);await create(page,'账号',{'平台':'OLD','登录网址':'https://a.example','账号':'a','密码':'p','备注':'','标签（逗号分隔）':''});await create(page,'网站',{'名称':'NEW','网址':'https://n.example','说明':'','标签（逗号分隔）':''});await page.locator('[data-type="account"]').click();await page.locator('.item-card').click();const result=await page.evaluate(state=>{document.querySelector('[data-type="website"]').click();return (0,eval)(`(${state})`)()},state.toString());assert.equal(result.detailDisplay,width<=650?'none':'block');assert.equal(result.oldText,false);assert.equal(result.active,'website');assert.match(result.list,/NEW/);assert.ok(result.cardOpacities.every(x=>Number(x)>0));await page.close()}}finally{await browser.close()}});
