import test from 'node:test';
import assert from 'node:assert/strict';
import worker from '../apps/worker/src/index.ts';
import { Miniflare } from 'miniflare';

class Result { constructor(results=[],meta={changes:0}){this.results=results;this.meta=meta;this.success=true} }
class DB {
  users=[]; sessions=[]; entries=[]; attempts=[]; attachments=[]; usage=[]; storage=0; failInsertAttachment=false; failBatch=false;
  prepare(sql){return new Statement(this,sql)}
  async batch(stmts){if(this.failBatch)throw Error('d1 batch failed');const out=[];for(const s of stmts)out.push(await s.run());return out}
}
class Statement {
  constructor(db,sql,args=[]){this.db=db;this.sql=sql.replace(/\s+/g,' ').trim();this.args=args}
  bind(...args){return new Statement(this.db,this.sql,args)}
  async first(){return (await this.all()).results[0]??null}
  async all(){const[d,s,a]=[this.db,this.sql,this.args];
    if(s.includes('FROM users WHERE username = ?'))return new Result(d.users.filter(x=>x.username===a[0]));
    if(s.includes('FROM sessions s JOIN users u'))return new Result(d.sessions.filter(x=>x.id_hash===a[0]&&x.expires_at>a[1]).map(x=>({...x,...d.users.find(u=>u.id===x.user_id)})));
    if(s.startsWith('SELECT id,type,version,iv,ciphertext,created_at FROM entries'))return new Result(d.entries.filter(x=>x.user_id===a[0]).map(({id,type,version,iv,ciphertext,created_at})=>({id,type,version,iv,ciphertext,created_at})));
    if(s.startsWith('SELECT id,type,version,iv,ciphertext FROM entries'))return new Result(d.entries.filter(x=>x.user_id===a[0]).map(({id,type,version,iv,ciphertext})=>({id,type,version,iv,ciphertext})));
    if(s.startsWith('SELECT id,metadata_iv'))return new Result(d.attachments.filter(x=>x.user_id===a[0]).map(x=>({...x})));
    if(s.startsWith('SELECT COUNT(*) AS count, COALESCE(SUM(ciphertext_size),0) AS total'))return new Result([{count:d.attachments.filter(x=>x.user_id===a[0]).length,total:d.attachments.filter(x=>x.user_id===a[0]).reduce((n,x)=>n+x.ciphertext_size,0)}]);
    if(s.startsWith('SELECT COALESCE(SUM(ciphertext_size),0) AS total FROM attachments'))return new Result([{total:d.attachments.reduce((n,x)=>n+x.ciphertext_size,0)}]);
    if(s.startsWith('SELECT 1 FROM attachments'))return new Result(d.attachments.filter(x=>x.user_id===a[0]&&x.id===a[1]));
    if(s.startsWith('SELECT * FROM attachments'))return new Result(d.attachments.filter(x=>x.user_id===a[0]&&x.id===a[1]));
    if(s.startsWith('SELECT COUNT(*) AS count FROM login_attempts')||s.startsWith('SELECT COUNT(*) AS count FROM invite_attempts'))return new Result([{count:d.attempts.filter(x=>x.key===a[0]&&x.attempted_at>a[1]).length}]);
    throw Error('Unhandled all SQL: '+s)
  }
  async run(){const[d,s,a]=[this.db,this.sql,this.args];
    if(s.startsWith('INSERT INTO r2_monthly_usage')){if(!d.usage.some(x=>x.month===a[0]))d.usage.push({month:a[0],class_a:0,class_b:0});return new Result([],{changes:1})}
    if(s.startsWith('INSERT INTO r2_storage_usage')){d.storage=Math.max(d.storage,a[0]);return new Result([],{changes:1})}
    if(s.startsWith('UPDATE r2_monthly_usage SET')){const kind=s.includes('class_a=')?'class_a':'class_b',x=d.usage.find(x=>x.month===a[1]);if(x&&x[kind]+a[0]<=a[3]){x[kind]+=a[0];return new Result([],{changes:1})}return new Result()}
    if(s.startsWith('UPDATE r2_storage_usage')){if(d.storage+a[0]>=0&&d.storage+a[0]<=a[3]){d.storage+=a[0];return new Result([],{changes:1})}return new Result()}
    if(s.startsWith('INSERT INTO users')){d.users.push({id:a[0],username:a[1],password_hash:a[2],password_salt:a[3],kdf:a[4],wrapped_key:a[5],created_at:a[6]});return new Result([], {changes:1})}
    if(s.startsWith('INSERT INTO sessions')){d.sessions.push({id_hash:a[0],user_id:a[1],csrf_hash:a[2],expires_at:a[3]});return new Result([], {changes:1})}
    if(s.startsWith('INSERT INTO login_attempts')||s.startsWith('INSERT INTO invite_attempts')){d.attempts.push({key:a[0],attempted_at:a[1]});return new Result([], {changes:1})}
    if(s.startsWith('DELETE FROM login_attempts')||s.startsWith('DELETE FROM invite_attempts')){d.attempts=d.attempts.filter(x=>!(x.key===a[0]||x.attempted_at<a.at(-1)));return new Result([], {changes:1})}
    if(s.startsWith('DELETE FROM sessions WHERE id_hash')){const n=d.sessions.length;d.sessions=d.sessions.filter(x=>x.id_hash!==a[0]);return new Result([], {changes:n-d.sessions.length})}
    if(s.startsWith('DELETE FROM sessions WHERE user_id = ? AND id_hash')){d.sessions=d.sessions.filter(x=>!(x.user_id===a[0]&&x.id_hash!==a[1]));return new Result([], {changes:1})}
    if(s.startsWith('DELETE FROM sessions WHERE user_id')){d.sessions=d.sessions.filter(x=>x.user_id!==a[0]);return new Result([], {changes:1})}
    if(s.startsWith('UPDATE users SET kdf=')){const u=d.users.find(x=>x.id===a[2]);Object.assign(u,{kdf:a[0],wrapped_key:a[1]});return new Result([], {changes:1})}
    if(s.startsWith('UPDATE users SET username=')){if(d.users.some(x=>x.username===a[0]&&x.id!==a[1]))throw Error('UNIQUE constraint failed: users.username');d.users.find(x=>x.id===a[1]).username=a[0];return new Result([], {changes:1})}
    if(s.startsWith('UPDATE users SET')){const u=d.users.find(x=>x.id===a[4]);Object.assign(u,{password_hash:a[0],password_salt:a[1],kdf:a[2],wrapped_key:a[3]});return new Result([], {changes:1})}
    if(s.startsWith('INSERT INTO entries')){const old=d.entries.find(e=>e.user_id===a[0]&&e.id===a[1]),x={user_id:a[0],id:a[1],type:a[2],version:a[3],iv:a[4],ciphertext:a[5],created_at:old?.created_at??a[6],updated_at:a[7]??a[6]};d.entries=d.entries.filter(e=>!(e.user_id===x.user_id&&e.id===x.id));d.entries.push(x);return new Result([], {changes:1})}
    if(s.startsWith('DELETE FROM entries WHERE user_id = ? AND id')){const n=d.entries.length;d.entries=d.entries.filter(x=>!(x.user_id===a[0]&&x.id===a[1]));return new Result([], {changes:n-d.entries.length})}
    if(s.startsWith('DELETE FROM entries WHERE user_id')){d.entries=d.entries.filter(x=>x.user_id!==a[0]);return new Result([], {changes:1})}
    if(s.startsWith('INSERT INTO attachments')){if(d.failInsertAttachment)throw Error('d1 failed');d.attachments.push({user_id:a[0],id:a[1],metadata_iv:a[2],metadata_ciphertext:a[3],object_key:a[4],ciphertext_size:a[5],created_at:a[6],updated_at:a[7]});return new Result([],{changes:1})}
    if(s.startsWith('UPDATE attachments')){const x=d.attachments.find(x=>x.user_id===a[3]&&x.id===a[4]);Object.assign(x,{metadata_iv:a[0],metadata_ciphertext:a[1],updated_at:a[2]});return new Result([],{changes:1})}
    if(s.startsWith('DELETE FROM attachments')){const n=d.attachments.length;d.attachments=d.attachments.filter(x=>!(x.user_id===a[0]&&x.id===a[1]));return new Result([],{changes:n-d.attachments.length})}
    if(s.startsWith('DELETE FROM sessions WHERE expires_at'))return new Result();
    throw Error('Unhandled run SQL: '+s)
  }
}
class R2 { objects=new Map(); failPut=false; failDelete=false; async put(k,v){if(this.failPut)throw Error('r2 put failed');this.objects.set(k,new Uint8Array(await new Response(v).arrayBuffer()))} async get(k){const v=this.objects.get(k);return v&&{body:v}} async delete(k){if(this.failDelete)throw Error('r2 delete failed');this.objects.delete(k)} }
const env=()=>({DB:new DB(),ATTACHMENTS:new R2(),ASSETS:{fetch:()=>new Response('asset')},INVITE_CODE:'test-invite-code-1234567890'});
const call=(env,path,{method='GET',body,raw,headers={}}={})=>worker.fetch(new Request('https://vault.test'+path,{method,headers:{...(body?{'content-type':'application/json'}:{}),...headers},body:raw??(body&&JSON.stringify(body))}),env,{waitUntil(){}});
const creds={username:'alice',password:'correct horse battery',inviteCode:'test-invite-code-1234567890',kdf:{salt:'client-salt',iterations:310000},wrappedKey:{iv:'opaque-iv',ciphertext:'opaque-wrapped-vault-key'}};
async function login(e){await call(e,'/api/register',{method:'POST',body:creds});const r=await call(e,'/api/login',{method:'POST',body:{username:creds.username,password:creds.password},headers:{'CF-Connecting-IP':'1.2.3.4'}});return {json:await r.json(),cookie:r.headers.get('set-cookie').split(';')[0]}}

test('Worker 注册邀请码关闭、拒绝、持久限速与成功',async()=>{const missing=env();delete missing.INVITE_CODE;let r=await call(missing,'/api/register',{method:'POST',body:creds,headers:{'CF-Connecting-IP':'7.7.7.7'}});assert.equal(r.status,503);assert.deepEqual(await r.json(),{error:'registration_unavailable'});assert.equal(missing.DB.users.length,0);const e=env();for(let i=0;i<10;i++){r=await call(e,'/api/register',{method:'POST',body:{...creds,inviteCode:'wrong-invite-code-123456789'},headers:{'CF-Connecting-IP':'8.8.8.8'}});assert.equal(r.status,403)}r=await call(e,'/api/register',{method:'POST',body:creds,headers:{'CF-Connecting-IP':'8.8.8.8'}});assert.equal(r.status,429);assert.equal(e.DB.users.length,0);r=await call(env(),'/api/register',{method:'POST',body:creds,headers:{'CF-Connecting-IP':'9.9.9.9'}});assert.equal(r.status,201)});

test('静态资源和 API 都返回生产安全头',async()=>{const e=env();for(const path of ['/', '/api/health']){const r=await call(e,path),csp=r.headers.get('content-security-policy');assert.match(csp,/frame-ancestors 'none'/);assert.match(csp,/script-src 'self'/);assert.match(csp,/img-src 'self' data: blob:/);assert.match(csp,/media-src 'self' blob:/);assert.match(csp,/frame-src 'self' blob:/);assert.doesNotMatch(csp,/script-src[^;]*(?:'unsafe-inline'|'unsafe-eval'|blob:)/);assert.equal(r.headers.get('strict-transport-security'),'max-age=63072000; includeSubDomains; preload');assert.equal(r.headers.get('x-content-type-options'),'nosniff');assert.equal(r.headers.get('x-frame-options'),'DENY');assert.equal(r.headers.get('referrer-policy'),'no-referrer')}});

test('完整认证、会话、CSRF、密文 CRUD、备份和改密流程',async()=>{const e=env();const a=await login(e);assert.equal(typeof a.json.csrf,'string');assert.equal((await call(e,'/api/session',{headers:{cookie:a.cookie}})).status,200);
  assert.deepEqual(a.json.kdf,creds.kdf);assert.deepEqual(a.json.wrappedKey,creds.wrappedKey);assert.equal(typeof e.DB.users[0].kdf,'string');assert.equal(typeof e.DB.users[0].wrapped_key,'string');
  const envelope={id:'entry_123',type:'account',version:1,iv:'opaque-iv',ciphertext:'opaque-ciphertext'};
  assert.equal((await call(e,'/api/entries/entry_123',{method:'PUT',body:envelope,headers:{cookie:a.cookie,origin:'https://vault.test','x-csrf-token':a.json.csrf}})).status,200);
  const list=await (await call(e,'/api/entries',{headers:{cookie:a.cookie}})).json();assert.deepEqual(list.items.map(({createdAt,...x})=>x),[envelope]);assert.ok(Number.isSafeInteger(list.items[0].createdAt));assert.equal(JSON.stringify(e.DB).includes(creds.password),false);
  const backup=await (await call(e,'/api/backup',{headers:{cookie:a.cookie}})).json();assert.deepEqual(backup,{version:1,kdf:creds.kdf,wrappedKey:creds.wrappedKey,envelopes:[envelope]});
  assert.equal((await call(e,'/api/backup',{method:'PUT',body:backup,headers:{cookie:a.cookie,origin:'https://vault.test','x-csrf-token':a.json.csrf}})).status,200);
  const changed=await call(e,'/api/change-password',{method:'POST',body:{currentPassword:creds.password,newPassword:'another secure password',kdf:{salt:'new-salt',iterations:310000,hash:'SHA-256'},wrappedKey:{iv:'new-iv',ciphertext:'new-wrap'}},headers:{cookie:a.cookie,origin:'https://vault.test','x-csrf-token':a.json.csrf}});assert.equal(changed.status,200);assert.match(changed.headers.get('set-cookie'),/Max-Age=0/);
  assert.equal((await call(e,'/api/entries/entry_123',{method:'DELETE',headers:{cookie:a.cookie,origin:'https://vault.test','x-csrf-token':a.json.csrf}})).status,401);
});
test('Worker 条目创建时间由后端生成、列表返回且编辑不可改变',async()=>{const e=env(),a=await login(e),headers={cookie:a.cookie,origin:'https://vault.test','x-csrf-token':a.json.csrf},entry={id:'created_123',type:'note',version:1,iv:'opaque-iv',ciphertext:'opaque-ciphertext'};let r=await call(e,'/api/entries/created_123',{method:'PUT',headers,body:{...entry,createdAt:1}});assert.equal(r.status,400);r=await call(e,'/api/entries/created_123',{method:'PUT',headers,body:entry});const createdAt=(await r.json()).createdAt;assert.ok(Number.isSafeInteger(createdAt));await new Promise(resolve=>setTimeout(resolve,2));r=await call(e,'/api/entries/created_123',{method:'PUT',headers,body:{...entry,ciphertext:'edited'}});assert.equal((await r.json()).createdAt,createdAt);assert.equal((await (await call(e,'/api/entries',{headers:{cookie:a.cookie}})).json()).items[0].createdAt,createdAt)});
test('真实前端密钥对象可注册且旧字符串和畸形对象被拒绝',async()=>{for(const bad of [
  {...creds,kdf:JSON.stringify(creds.kdf)},
  {...creds,wrappedKey:JSON.stringify(creds.wrappedKey)},
  {...creds,kdf:{salt:'x',iterations:1}},
  {...creds,kdf:{salt:'x',iterations:310000,hash:'SHA-1'}},
  {...creds,wrappedKey:{iv:'x'}},
]){const e=env();const r=await call(e,'/api/register',{method:'POST',body:bad});assert.equal(r.status,400);assert.deepEqual(await r.json(),{error:'invalid'})}});
test('拒绝跨源、明文 envelope、错误密码并实施登录限速',async()=>{const e=env();const a=await login(e);const bad={id:'entry_123',type:'account',version:1,iv:'iv',ciphertext:'cipher',password:'leak'};
  assert.equal((await call(e,'/api/entries/entry_123',{method:'PUT',body:bad,headers:{cookie:a.cookie,origin:'https://evil.test','x-csrf-token':a.json.csrf}})).status,403);
  assert.equal((await call(e,'/api/entries/entry_123',{method:'PUT',body:bad,headers:{cookie:a.cookie,origin:'https://vault.test','x-csrf-token':a.json.csrf}})).status,400);
  for(let i=0;i<10;i++)assert.equal((await call(e,'/api/login',{method:'POST',body:{username:'alice',password:'wrong password!'},headers:{'CF-Connecting-IP':'9.9.9.9'}})).status,401);
  assert.equal((await call(e,'/api/login',{method:'POST',body:{username:'alice',password:'wrong password!'},headers:{'CF-Connecting-IP':'9.9.9.9'}})).status,429);
});
test('改密区分当前密码与新密钥材料错误，并清除当前会话 cookie',async()=>{const e=env(),a=await login(e),headers={cookie:a.cookie,origin:'https://vault.test','x-csrf-token':a.json.csrf};
  let r=await call(e,'/api/change-password',{method:'POST',headers,body:{currentPassword:'wrong password here',newPassword:'another secure password',kdf:{salt:'new-salt',iterations:310000},wrappedKey:{iv:'new-iv',ciphertext:'new-wrap'}}});
  assert.equal(r.status,401);assert.deepEqual(await r.json(),{error:'invalid_current_password'});
  for(const [body,code] of [[{currentPassword:creds.password,newPassword:'short',kdf:{salt:'new-salt',iterations:310000},wrappedKey:{iv:'new-iv',ciphertext:'new-wrap'}},'invalid_new_password'],[{currentPassword:creds.password,newPassword:'another secure password',kdf:{salt:'bad',iterations:1},wrappedKey:{iv:'new-iv',ciphertext:'new-wrap'}},'invalid_key_material']]){r=await call(e,'/api/change-password',{method:'POST',headers,body});assert.equal(r.status,400);assert.deepEqual(await r.json(),{error:code})}
  r=await call(e,'/api/change-password',{method:'POST',headers,body:{currentPassword:creds.password,newPassword:'another secure password',kdf:{salt:'new-salt',iterations:310000},wrappedKey:{iv:'new-iv',ciphertext:'new-wrap'}}});
  assert.equal(r.status,200);assert.match(r.headers.get('set-cookie'),/Max-Age=0/);assert.equal((await call(e,'/api/session',{headers:{cookie:a.cookie}})).status,401);
});
test('改用户名严格校验、验证当前密码、撤销全部会话且不改变密钥材料或密文',async()=>{const e=env(),a=await login(e),headers={cookie:a.cookie,origin:'https://vault.test','x-csrf-token':a.json.csrf},envelope={id:'entry_123',type:'note',version:1,iv:'opaque-iv',ciphertext:'opaque-ciphertext'};await call(e,'/api/entries/entry_123',{method:'PUT',body:envelope,headers});const second=await call(e,'/api/login',{method:'POST',body:{username:creds.username,password:creds.password},headers:{'CF-Connecting-IP':'2'}}),secondCookie=second.headers.get('set-cookie').split(';')[0],before={kdf:e.DB.users[0].kdf,wrapped:e.DB.users[0].wrapped_key,entry:structuredClone(e.DB.entries[0])};
 for(const [body,status,code] of [[{newUsername:'new alice'},400,'invalid_request'],[{newUsername:'new alice',currentPassword:'wrong password here'},401,'invalid_current_password'],[{newUsername:'\0bad',currentPassword:creds.password},400,'invalid_username']]){const r=await call(e,'/api/change-username',{method:'POST',body,headers});assert.equal(r.status,status);assert.deepEqual(await r.json(),{error:code});assert.equal(e.DB.users[0].username,'alice');assert.equal((await call(e,'/api/session',{headers:{cookie:a.cookie}})).status,200)}
 await call(e,'/api/register',{method:'POST',body:{...creds,username:'taken'}});let r=await call(e,'/api/change-username',{method:'POST',body:{newUsername:'taken',currentPassword:creds.password},headers});assert.equal(r.status,409);assert.deepEqual(await r.json(),{error:'username_taken'});r=await call(e,'/api/change-username',{method:'POST',body:{newUsername:'  新 用户 🚀  ',currentPassword:creds.password},headers});assert.equal(r.status,200);assert.match(r.headers.get('set-cookie'),/Max-Age=0/);assert.equal((await call(e,'/api/session',{headers:{cookie:a.cookie}})).status,401);assert.equal((await call(e,'/api/session',{headers:{cookie:secondCookie}})).status,401);assert.equal((await call(e,'/api/login',{method:'POST',body:{username:'alice',password:creds.password},headers:{'CF-Connecting-IP':'3'}})).status,401);assert.equal((await call(e,'/api/login',{method:'POST',body:{username:'新 用户 🚀',password:creds.password},headers:{'CF-Connecting-IP':'4'}})).status,200);assert.deepEqual({kdf:e.DB.users[0].kdf,wrapped:e.DB.users[0].wrapped_key,entry:e.DB.entries[0]},before)
});

const metadata={version:1,iv:'metadata-iv',ciphertext:'encrypted-metadata'};
test('Worker R2 附件 CRUD、CSRF、IDOR 与失败一致性',async()=>{const e=env(),a=await login(e),h={cookie:a.cookie,origin:'https://vault.test','x-csrf-token':a.json.csrf},bytes=new Uint8Array(16).fill(7),mh={...h,'content-length':'16','x-attachment-metadata':JSON.stringify(metadata)};
 let r=await call(e,'/api/attachments/attach_123',{method:'POST',raw:bytes,headers:mh});assert.equal(r.status,201);assert.equal(e.ATTACHMENTS.objects.size,1);assert.equal((await (await call(e,'/api/attachments',{headers:{cookie:a.cookie}})).json()).items.length,1);r=await call(e,'/api/attachments/attach_123/content',{headers:{cookie:a.cookie}});assert.deepEqual(new Uint8Array(await r.arrayBuffer()),bytes);
 r=await call(e,'/api/attachments/attach_123/metadata',{method:'PUT',body:{version:1,iv:'new',ciphertext:'cipher'},headers:h});assert.equal(r.status,200);assert.equal((await call(e,'/api/attachments/attach_123',{method:'DELETE',headers:{...h,'x-csrf-token':'bad'}})).status,403);
 const b={...e,DB:e.DB},bob={...creds,username:'bob'};await call(b,'/api/register',{method:'POST',body:bob});const lr=await call(b,'/api/login',{method:'POST',body:{username:'bob',password:creds.password},headers:{'CF-Connecting-IP':'2'}});assert.equal((await call(b,'/api/attachments/attach_123/content',{headers:{cookie:lr.headers.get('set-cookie').split(';')[0]}})).status,404);
 assert.equal((await call(e,'/api/attachments/attach_123',{method:'DELETE',headers:h})).status,204);assert.equal(e.ATTACHMENTS.objects.size,0);
 e.ATTACHMENTS.failPut=true;assert.equal((await call(e,'/api/attachments/attach_456',{method:'POST',raw:bytes,headers:mh})).status,500);assert.equal(e.DB.attachments.length,0);e.ATTACHMENTS.failPut=false;e.DB.failInsertAttachment=true;assert.equal((await call(e,'/api/attachments/attach_456',{method:'POST',raw:bytes,headers:mh})).status,500);assert.equal(e.ATTACHMENTS.objects.size,0);
});
test('真实 Miniflare R2 接受固定长度二进制值',async()=>{const mf=new Miniflare({modules:true,compatibilityDate:'2026-07-11',r2Buckets:['ATTACHMENTS'],script:`export default {async fetch(req,env){const bytes=await req.arrayBuffer();const object=await env.ATTACHMENTS.put('probe',bytes);return new Response(String(object.size))}}`});try{const r=await mf.dispatchFetch('https://vault.test/upload',{method:'POST',headers:{'content-length':'16'},body:new Uint8Array(16)});assert.equal(r.status,200);assert.equal(await r.text(),'16')}finally{await mf.dispose()}});
test('Worker 上传要求可信 Content-Length 并在写 R2 前拒绝无长度、伪长度和超限',async()=>{const e=env(),a=await login(e),h={cookie:a.cookie,origin:'https://vault.test','x-csrf-token':a.json.csrf,'x-attachment-metadata':JSON.stringify(metadata)};let r=await call(e,'/api/attachments/attach_123',{method:'POST',raw:new Uint8Array(16),headers:h});assert.equal(r.status,411);r=await call(e,'/api/attachments/attach_456',{method:'POST',raw:new Uint8Array(16),headers:{...h,'content-length':'17'}});assert.equal(r.status,400);r=await call(e,'/api/attachments/attach_789',{method:'POST',raw:new Uint8Array(20*1024*1024+17),headers:{...h,'content-length':String(20*1024*1024+17)}});assert.equal(r.status,413);assert.equal(e.DB.attachments.length,0)});
test('Worker 上传所有失败路径准确释放 storage 预留但保守保留 Class A',async()=>{const e=env(),a=await login(e),base={cookie:a.cookie,origin:'https://vault.test','x-csrf-token':a.json.csrf},bytes=new Uint8Array(16),good={...base,'content-length':'16','x-attachment-metadata':JSON.stringify(metadata)};
  e.ATTACHMENTS.failPut=true;assert.equal((await call(e,'/api/attachments/fail_r2_1',{method:'POST',raw:bytes,headers:good})).status,500);assert.equal(e.DB.storage,0);assert.equal(e.DB.usage[0].class_a,1);
  e.ATTACHMENTS.failPut=false;e.DB.failInsertAttachment=true;assert.equal((await call(e,'/api/attachments/fail_d1_1',{method:'POST',raw:bytes,headers:good})).status,500);assert.equal(e.DB.storage,0);assert.equal(e.DB.usage[0].class_a,2);assert.equal(e.ATTACHMENTS.objects.size,0);
  e.DB.failInsertAttachment=false;assert.equal((await call(e,'/api/attachments/fail_len1',{method:'POST',raw:bytes,headers:{...good,'content-length':'17'}})).status,400);assert.equal(e.DB.storage,0);
  assert.equal((await call(e,'/api/attachments/fail_meta',{method:'POST',raw:bytes,headers:{...good,'x-attachment-metadata':'{'}})).status,400);assert.equal(e.DB.storage,0);assert.equal(e.DB.usage[0].class_a,2);
});
test('Worker 删除 R2 失败时保留 DB 引用供重试',async()=>{const e=env(),a=await login(e),h={cookie:a.cookie,origin:'https://vault.test','x-csrf-token':a.json.csrf},mh={...h,'content-length':'16','x-attachment-metadata':JSON.stringify(metadata)};await call(e,'/api/attachments/retry_123',{method:'POST',raw:new Uint8Array(16),headers:mh});e.ATTACHMENTS.failDelete=true;assert.equal((await call(e,'/api/attachments/retry_123',{method:'DELETE',headers:h})).status,500);assert.equal(e.DB.attachments.length,1);e.ATTACHMENTS.failDelete=false;assert.equal((await call(e,'/api/attachments/retry_123',{method:'DELETE',headers:h})).status,204);assert.equal(e.DB.attachments.length,0)});
test('Worker 备份 v2 往返且 v1 兼容，并拒绝损坏附件',async()=>{const e=env(),a=await login(e),h={cookie:a.cookie,origin:'https://vault.test','x-csrf-token':a.json.csrf};await call(e,'/api/attachments/attach_123',{method:'POST',raw:new Uint8Array(16).fill(3),headers:{...h,'content-length':'16','x-attachment-metadata':JSON.stringify(metadata)}});const backup=await (await call(e,'/api/backup?attachments=1',{headers:{cookie:a.cookie}})).json();assert.equal(backup.version,2);assert.ok(Array.isArray(backup.entries));assert.equal(backup.attachments.length,1);assert.ok(backup.attachments[0].sha256);assert.equal((await call(e,'/api/backup',{method:'PUT',body:backup,headers:h})).status,200);assert.equal((await call(e,'/api/backup',{method:'PUT',body:{version:1,kdf:backup.kdf,wrappedKey:backup.wrappedKey,envelopes:[]},headers:h})).status,200);for(const mutate of [x=>x.attachments.push({...x.attachments[0]}),x=>delete x.attachments[0].object,x=>x.attachments[0].ciphertextSize++,x=>x.attachments[0].sha256='bad']){const x=structuredClone(backup);mutate(x);assert.equal((await call(e,'/api/backup',{method:'PUT',body:x,headers:h})).status,400)}});
test('Worker 替换附件失败时释放新旧 storage 差值且保留旧附件',async()=>{const e=env(),a=await login(e),h={cookie:a.cookie,origin:'https://vault.test','x-csrf-token':a.json.csrf};await call(e,'/api/attachments/old_item1',{method:'POST',raw:new Uint8Array(16).fill(3),headers:{...h,'content-length':'16','x-attachment-metadata':JSON.stringify(metadata)}});const backup=await (await call(e,'/api/backup?attachments=1',{headers:{cookie:a.cookie}})).json();backup.attachments[0].object=btoa(String.fromCharCode(...new Uint8Array(20).fill(4)));backup.attachments[0].ciphertextSize=20;backup.attachments[0].sha256=await (async()=>{const b=await crypto.subtle.digest('SHA-256',new Uint8Array(20).fill(4));return Buffer.from(b).toString('base64url')})();
  e.DB.failBatch=true;const beforeA=e.DB.usage[0].class_a;assert.equal((await call(e,'/api/backup',{method:'PUT',body:backup,headers:h})).status,500);assert.equal(e.DB.storage,16);assert.equal(e.DB.attachments[0].id,'old_item1');assert.equal(e.ATTACHMENTS.objects.size,1);assert.equal(e.DB.usage[0].class_a,beforeA+1);
});
