import { createServer } from 'node:http';
import { readFile, mkdir } from 'node:fs/promises';
import { join, extname, dirname, resolve } from 'node:path';
import { randomBytes, randomUUID, scryptSync, timingSafeEqual, createHash } from 'node:crypto';
import { DatabaseSync } from 'node:sqlite';
import { validEnvelope, validKdf, validWrappedKey, validateUsername } from '../../shared/contract.mjs';

const HOST=process.env.HOST||'127.0.0.1',PORT=Number(process.env.PORT||3000);
const DB_PATH=resolve(process.env.DB_PATH||join(process.cwd(),'data','pass-vault.sqlite'));
await mkdir(dirname(DB_PATH),{recursive:true});
const db=new DatabaseSync(DB_PATH);db.exec(`PRAGMA foreign_keys=ON; PRAGMA journal_mode=WAL; PRAGMA synchronous=FULL;
CREATE TABLE IF NOT EXISTS users(id TEXT PRIMARY KEY,username TEXT UNIQUE NOT NULL,password_hash TEXT NOT NULL,password_salt TEXT NOT NULL,kdf TEXT NOT NULL,wrapped_key TEXT NOT NULL,created_at INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS sessions(id_hash TEXT PRIMARY KEY,user_id TEXT NOT NULL,csrf_hash TEXT NOT NULL,expires_at INTEGER NOT NULL,FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE);
CREATE TABLE IF NOT EXISTS entries(user_id TEXT NOT NULL,id TEXT NOT NULL,type TEXT NOT NULL CHECK(type IN('account','website','note')),version INTEGER NOT NULL,iv TEXT NOT NULL,ciphertext TEXT NOT NULL,updated_at INTEGER NOT NULL,PRIMARY KEY(user_id,id),FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE);
CREATE INDEX IF NOT EXISTS idx_entries_user_type ON entries(user_id,type);`);
const attempts=new Map(),cookieName='pv_session',SESSION_MS=8*60*60*1000,MAX_BODY=2_000_000;
const digest=x=>createHash('sha256').update(x).digest('hex');
const passwordHash=(p,s=randomBytes(16))=>({salt:s.toString('base64'),hash:scryptSync(p,s,32,{N:32768,maxmem:64*1024*1024}).toString('base64')});
function verify(p,u){try{const a=scryptSync(p,Buffer.from(u.password_salt,'base64'),32,{N:32768,maxmem:64*1024*1024}),b=Buffer.from(u.password_hash,'base64');return a.length===b.length&&timingSafeEqual(a,b)}catch{return false}}
const json=(res,status,value,headers={})=>{res.writeHead(status,{'content-type':'application/json; charset=utf-8','cache-control':'no-store','x-content-type-options':'nosniff','x-frame-options':'DENY','referrer-policy':'no-referrer','content-security-policy':"default-src 'self'; object-src 'none'; frame-ancestors 'none'",...headers});res.end(status===204?'':JSON.stringify(value))};
async function body(req){let size=0,chunks=[];for await(const c of req){size+=c.length;if(size>MAX_BODY)throw Object.assign(new Error('too_large'),{status:413});chunks.push(c)}try{return JSON.parse(Buffer.concat(chunks).toString()||'{}')}catch{throw Object.assign(new Error('invalid_json'),{status:400})}}
const validWrapped=validWrappedKey;
const validPassword=x=>typeof x==='string'&&x.length>=12&&x.length<=1024;
function requestOrigin(req){const proto=(req.headers['x-forwarded-proto']||'').split(',')[0].trim()||'http';return `${proto}://${req.headers.host}`}
function csrf(req,s){const supplied=req.headers['x-csrf-token'];return typeof supplied==='string'&&digest(supplied)===s.csrf_hash&&req.headers.origin===requestOrigin(req)}
function auth(req){db.prepare('DELETE FROM sessions WHERE expires_at<=?').run(Date.now());const raw=(req.headers.cookie||'').split(';').map(v=>v.trim().split('=')).find(v=>v[0]===cookieName)?.[1];if(!raw)return null;return db.prepare('SELECT s.*,u.username FROM sessions s JOIN users u ON u.id=s.user_id WHERE s.id_hash=? AND s.expires_at>?').get(digest(raw),Date.now())||null}
function limited(ip){const now=Date.now(),a=(attempts.get(ip)||[]).filter(t=>t>now-60_000);a.push(now);attempts.set(ip,a);return a.length>10}
function cookie(raw,maxAge=28800){const secure=process.env.COOKIE_SECURE!=='false';return `${cookieName}=${raw}; HttpOnly; ${secure?'Secure; ':''}SameSite=Strict; Path=/; Max-Age=${maxAge}`}
function envelope(row){return{id:row.id,type:row.type,version:row.version,iv:row.iv,ciphertext:row.ciphertext}}
function userMaterial(userId){const u=db.prepare('SELECT kdf,wrapped_key FROM users WHERE id=?').get(userId);return{kdf:JSON.parse(u.kdf),wrappedKey:JSON.parse(u.wrapped_key)}}

const server=createServer(async(req,res)=>{try{const url=new URL(req.url,'http://localhost'),p=url.pathname;if(p.startsWith('/api/')){
 if(req.method==='GET'&&p==='/api/health')return json(res,200,{ok:true,backend:'sqlite'});
 if(req.method==='POST'&&p==='/api/register'){const x=await body(req),name=validateUsername(x.username);if(!name.valid)return json(res,400,{error:'invalid_username'});if(!validPassword(x.password)||!validKdf(x.kdf)||!validWrapped(x.wrappedKey))return json(res,400,{error:'invalid'});const h=passwordHash(x.password);try{db.prepare('INSERT INTO users(id,username,password_hash,password_salt,kdf,wrapped_key,created_at) VALUES(?,?,?,?,?,?,?)').run(randomUUID(),name.value,h.hash,h.salt,JSON.stringify(x.kdf),JSON.stringify(x.wrappedKey),Date.now())}catch(e){if(String(e).includes('UNIQUE'))return json(res,409,{error:'username_taken'});throw e}return json(res,201,{ok:true})}
 if(req.method==='POST'&&p==='/api/login'){if(limited(req.socket.remoteAddress||'unknown'))return json(res,429,{error:'rate_limited'});const x=await body(req),name=validateUsername(x.username);if(!name.valid)return json(res,400,{error:'invalid_username'});const u=db.prepare('SELECT * FROM users WHERE username=?').get(name.value);if(!u||!validPassword(x.password)||!verify(x.password,u))return json(res,401,{error:'invalid_credentials'});const raw=randomBytes(32).toString('base64url'),token=randomBytes(24).toString('base64url');db.prepare('INSERT INTO sessions VALUES(?,?,?,?)').run(digest(raw),u.id,digest(token),Date.now()+SESSION_MS);return json(res,200,{csrf:token,...userMaterial(u.id)},{'set-cookie':cookie(raw)})}
 const s=auth(req);if(!s)return json(res,401,{error:'unauthorized'});if(req.method!=='GET'&&!csrf(req,s))return json(res,403,{error:'csrf'});
 if(req.method==='GET'&&p==='/api/session')return json(res,200,{username:s.username,...userMaterial(s.user_id)});
 if(req.method==='GET'&&p==='/api/entries'){const rows=db.prepare('SELECT id,type,version,iv,ciphertext FROM entries WHERE user_id=? ORDER BY id').all(s.user_id);return json(res,200,{items:rows.map(envelope)})}
 if(req.method==='PUT'&&p.startsWith('/api/entries/')){const id=decodeURIComponent(p.slice('/api/entries/'.length)),x=await body(req),e={...x,id};if(!validEnvelope(e)||Object.keys(e).some(k=>!['id','type','version','iv','ciphertext'].includes(k)))return json(res,400,{error:'invalid_envelope'});db.prepare(`INSERT INTO entries(user_id,id,type,version,iv,ciphertext,updated_at) VALUES(?,?,?,?,?,?,?) ON CONFLICT(user_id,id) DO UPDATE SET type=excluded.type,version=excluded.version,iv=excluded.iv,ciphertext=excluded.ciphertext,updated_at=excluded.updated_at`).run(s.user_id,e.id,e.type,e.version,e.iv,e.ciphertext,Date.now());return json(res,200,e)}
 if(req.method==='DELETE'&&p.startsWith('/api/entries/')){db.prepare('DELETE FROM entries WHERE user_id=? AND id=?').run(s.user_id,decodeURIComponent(p.slice('/api/entries/'.length)));return json(res,204,{})}
 if(req.method==='GET'&&p==='/api/backup'){const rows=db.prepare('SELECT id,type,version,iv,ciphertext FROM entries WHERE user_id=? ORDER BY id').all(s.user_id);const envelopes=rows.map(envelope);return json(res,200,{version:1,...userMaterial(s.user_id),envelopes})}
 if((req.method==='PUT'&&p==='/api/backup')||(req.method==='POST'&&p==='/api/backup/import')){const x=await body(req),items=x.envelopes??x.entries;if((x.version!==undefined&&x.version!==1)||!validKdf(x.kdf)||!validWrapped(x.wrappedKey)||!Array.isArray(items)||items.length>100000||items.some(e=>!validEnvelope(e)||Object.keys(e).some(k=>!['id','type','version','iv','ciphertext'].includes(k)))||new Set(items.map(e=>e.id)).size!==items.length)return json(res,400,{error:'invalid_backup'});db.exec('BEGIN IMMEDIATE');try{db.prepare('UPDATE users SET kdf=?,wrapped_key=? WHERE id=?').run(JSON.stringify(x.kdf),JSON.stringify(x.wrappedKey),s.user_id);db.prepare('DELETE FROM entries WHERE user_id=?').run(s.user_id);const put=db.prepare('INSERT INTO entries VALUES(?,?,?,?,?,?,?)');for(const e of items)put.run(s.user_id,e.id,e.type,e.version,e.iv,e.ciphertext,Date.now());db.exec('COMMIT')}catch(e){db.exec('ROLLBACK');throw e}return json(res,200,{ok:true,count:items.length})}
 if(req.method==='POST'&&p==='/api/change-password'){const x=await body(req),u=db.prepare('SELECT * FROM users WHERE id=?').get(s.user_id);if(!validPassword(x.currentPassword)||!verify(x.currentPassword,u))return json(res,401,{error:'invalid_current_password'});if(!validPassword(x.newPassword))return json(res,400,{error:'invalid_new_password'});if(!validKdf(x.kdf)||!validWrapped(x.wrappedKey))return json(res,400,{error:'invalid_key_material'});const h=passwordHash(x.newPassword);db.exec('BEGIN IMMEDIATE');try{db.prepare('UPDATE users SET password_hash=?,password_salt=?,kdf=?,wrapped_key=? WHERE id=?').run(h.hash,h.salt,JSON.stringify(x.kdf),JSON.stringify(x.wrappedKey),s.user_id);db.prepare('DELETE FROM sessions WHERE user_id=?').run(s.user_id);db.exec('COMMIT')}catch(e){db.exec('ROLLBACK');throw e}return json(res,200,{ok:true},{'set-cookie':cookie('',0)})}
 if(req.method==='POST'&&p==='/api/logout'){db.prepare('DELETE FROM sessions WHERE id_hash=?').run(s.id_hash);return json(res,200,{ok:true},{'set-cookie':cookie('',0)})}
 return json(res,404,{error:'not_found'});
 }
 const relative=p==='/'?'index.html':p.replace(/^\//,'');if(relative.includes('..'))return json(res,404,{error:'not_found'});const root=join(process.cwd(),'dist'),file=join(root,relative);const data=await readFile(file);const types={'.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.mjs':'text/javascript; charset=utf-8','.css':'text/css; charset=utf-8'};res.writeHead(200,{'content-type':types[extname(file)]||'application/octet-stream','x-content-type-options':'nosniff'});res.end(data);
 }catch(e){if(e?.code==='ENOENT')return json(res,404,{error:'not_found'});console.error('request failed',e?.message);json(res,e?.status||500,{error:e?.message==='too_large'?'too_large':e?.message==='invalid_json'?'invalid_json':'internal_error'})}});
server.listen(PORT,HOST,()=>console.log(`pass-vault server listening on ${HOST}:${PORT}`));
function shutdown(){server.close(()=>{db.close();process.exit(0)})}process.on('SIGTERM',shutdown);process.on('SIGINT',shutdown);
