export const TYPES=['account','website','note'];
export const ATTACHMENT_CATEGORIES=['image','video','other'];
export const ATTACHMENT_LIMITS=Object.freeze({image:10*1024*1024,video:100*1024*1024,other:25*1024*1024});
export const MAX_ATTACHMENT_CIPHERTEXT=ATTACHMENT_LIMITS.video+16;
const plainObject=x=>!!x&&typeof x==='object'&&!Array.isArray(x);
export function validateUsername(x){if(typeof x!=='string')return{valid:false,value:''};const value=x.trim();if(!value||value.length>80||/[\p{Cc}\p{Cf}]/u.test(value))return{valid:false,value:''};return{valid:true,value}}
export function validKdf(x){return plainObject(x)&&Object.keys(x).every(k=>['salt','iterations','hash'].includes(k))&&typeof x.salt==='string'&&x.salt.length>0&&x.salt.length<1000&&x.iterations===310000&&(x.hash===undefined||x.hash==='SHA-256')}
export function validWrappedKey(x){return plainObject(x)&&Object.keys(x).length===2&&typeof x.iv==='string'&&x.iv.length>0&&x.iv.length<1000&&typeof x.ciphertext==='string'&&x.ciphertext.length>0&&x.ciphertext.length<10000}
export function validKeyMaterial(x){return plainObject(x)&&validKdf(x.kdf)&&validWrappedKey(x.wrappedKey)}
const attachmentIdValid=x=>typeof x==='string'&&/^[a-zA-Z0-9_-]{8,80}$/.test(x);
export function validEnvelope(x){return x&&TYPES.includes(x.type)&&typeof x.id==='string'&&/^[a-zA-Z0-9_-]{8,80}$/.test(x.id)&&typeof x.ciphertext==='string'&&x.ciphertext.length<2_000_000&&typeof x.iv==='string'&&typeof x.version==='number'&&!('password'in x)&&!('username'in x)&&!('body'in x)}export function validatePlain(type,x){const keys={account:['platform','loginUrl','username','password','notes','tags'],website:['name','url','description','tags'],note:['title','body','tags','attachmentIds']}[type];if(!keys||!x||Object.keys(x).some(k=>!keys.includes(k)))return false;return keys.filter(k=>k!=='attachmentIds').every(k=>k in x)&&Array.isArray(x.tags)&&(type!=='note'||(x.attachmentIds===undefined||(Array.isArray(x.attachmentIds)&&x.attachmentIds.length<=20&&x.attachmentIds.every(attachmentIdValid))))}
export const validAttachmentId=x=>typeof x==='string'&&/^[a-zA-Z0-9_-]{8,80}$/.test(x);
export function attachmentAad(id){if(!validAttachmentId(id))throw new TypeError('invalid_attachment_id');return new TextEncoder().encode(`pass-vault-v2:attachment:1:${id}`)}
export function validateAttachmentMetadata(x){if(!plainObject(x)||Object.keys(x).some(k=>!['name','mime','size','category','noteId','contentIv'].includes(k)))return false;return typeof x.name==='string'&&x.name.length>0&&x.name.length<=255&&!/[\p{Cc}\p{Cf}]/u.test(x.name)&&typeof x.mime==='string'&&x.mime.length<=255&&Number.isSafeInteger(x.size)&&x.size>=0&&ATTACHMENT_CATEGORIES.includes(x.category)&&x.size<=ATTACHMENT_LIMITS[x.category]&&(x.noteId===undefined||(validAttachmentId(x.noteId)&&x.category==='image'))&&typeof x.contentIv==='string'&&/^[A-Za-z0-9+/]{16}$/.test(x.contentIv)}
export function validAttachmentEnvelope(x){return plainObject(x)&&Object.keys(x).length===3&&x.version===1&&typeof x.iv==='string'&&x.iv.length>0&&x.iv.length<1000&&typeof x.ciphertext==='string'&&x.ciphertext.length>0&&x.ciphertext.length<2_000_000}
export function validAttachmentRecord(x){return plainObject(x)&&Object.keys(x).every(k=>['id','metadata','ciphertextSize','createdAt','updatedAt'].includes(k))&&validAttachmentId(x.id)&&validAttachmentEnvelope(x.metadata)&&Number.isSafeInteger(x.ciphertextSize)&&x.ciphertextSize>=16&&x.ciphertextSize<=MAX_ATTACHMENT_CIPHERTEXT}