export const TYPES=['account','website','note'];
export const GROUP_TYPES=['account','website','note','attachment'];
export const SETTINGS_ID='settings_registry';
const ID_RE=/^[a-zA-Z0-9_-]{8,80}$/;
export const ATTACHMENT_CATEGORIES=['image','video','other'];
export const ATTACHMENT_LIMITS=Object.freeze({image:10*1024*1024,video:100*1024*1024,other:25*1024*1024});
export const MAX_ATTACHMENT_CIPHERTEXT=ATTACHMENT_LIMITS.video+16;
export const INVITE_CODE_BOUNDS=Object.freeze({min:16,max:256});
const plainObject=x=>!!x&&typeof x==='object'&&!Array.isArray(x);
export function validateUsername(x){if(typeof x!=='string')return{valid:false,value:''};const value=x.trim();if(!value||value.length>80||/[\p{Cc}\p{Cf}]/u.test(value))return{valid:false,value:''};return{valid:true,value}}
export const validInviteCode=x=>typeof x==='string'&&x.length>=INVITE_CODE_BOUNDS.min&&x.length<=INVITE_CODE_BOUNDS.max;
export function validKdf(x){return plainObject(x)&&Object.keys(x).every(k=>['salt','iterations','hash'].includes(k))&&typeof x.salt==='string'&&x.salt.length>0&&x.salt.length<1000&&x.iterations===310000&&(x.hash===undefined||x.hash==='SHA-256')}
export function validWrappedKey(x){return plainObject(x)&&Object.keys(x).length===2&&typeof x.iv==='string'&&x.iv.length>0&&x.iv.length<1000&&typeof x.ciphertext==='string'&&x.ciphertext.length>0&&x.ciphertext.length<10000}
export function validKeyMaterial(x){return plainObject(x)&&validKdf(x.kdf)&&validWrappedKey(x.wrappedKey)}
const attachmentIdValid=x=>typeof x==='string'&&/^[a-zA-Z0-9_-]{8,80}$/.test(x);
export function validEnvelope(x){return x&&(TYPES.includes(x.type)||(x.type==='settings'&&x.id===SETTINGS_ID))&&typeof x.id==='string'&&ID_RE.test(x.id)&&typeof x.ciphertext==='string'&&x.ciphertext.length<2_000_000&&typeof x.iv==='string'&&typeof x.version==='number'&&!('password'in x)&&!('username'in x)&&!('credentials'in x)&&!('body'in x)}
export const legacyVisibleEnvelopes=items=>items.filter(x=>TYPES.includes(x?.type));
export function normalizeGroupRegistry(x){if(!plainObject(x)||Object.keys(x).length!==GROUP_TYPES.length||Object.keys(x).some(k=>!GROUP_TYPES.includes(k)))return null;const out={};for(const type of GROUP_TYPES){const rows=x[type];if(!Array.isArray(rows)||rows.length>50)return null;const ids=new Set(),names=new Set();out[type]=[];for(const row of rows){if(!plainObject(row)||Object.keys(row).length!==2||!('id'in row)||!('name'in row)||!ID_RE.test(row.id)||typeof row.name!=='string')return null;const name=row.name.trim();if(!name||name.length>40||/[\p{Cc}\p{Cf}]/u.test(name)||ids.has(row.id)||names.has(name))return null;ids.add(row.id);names.add(name);out[type].push({id:row.id,name})}}return out}
const boundedString=(x,max)=>typeof x==='string'&&x.length<=max;
const validCredentials=x=>Array.isArray(x)&&x.length>=1&&x.length<=20&&x.every((row,index)=>plainObject(row)&&Object.keys(row).length===2&&Object.keys(row).every(k=>['username','password'].includes(k))&&boundedString(row.username,256)&&boundedString(row.password,4096)&&((row.username.length>0&&row.password.length>0)||(x.length===1&&index===0&&row.username.length===0&&row.password.length===0)));
export function normalizePlain(type,x){if(type!=='account'||!plainObject(x))return x;if(Array.isArray(x.credentials))return x;if(typeof x.username!=='string'||typeof x.password!=='string')return x;const {username,password,...rest}=x;return{...rest,credentials:[{username,password}]}}
export function validatePlain(type,x){if(!plainObject(x)||('groupId'in x&&!ID_RE.test(x.groupId))||('pinned'in x&&typeof x.pinned!=='boolean')||('pinRank'in x&&(!Number.isSafeInteger(x.pinRank)||x.pinRank<0||x.pinRank>1000000||x.pinned!==true)))return false;if(type==='account'){const legacy='username'in x||'password'in x,keys=legacy?['platform','loginUrl','username','password','notes','tags','groupId','pinned','pinRank']:['platform','loginUrl','credentials','notes','tags','groupId','pinned','pinRank'];if(Object.keys(x).some(k=>!keys.includes(k))||keys.filter(k=>!['groupId','pinned','pinRank'].includes(k)).some(k=>!(k in x))||!Array.isArray(x.tags))return false;return boundedString(x.platform,256)&&boundedString(x.loginUrl,2048)&&boundedString(x.notes,10000)&&(legacy?(typeof x.username==='string'&&typeof x.password==='string'&&boundedString(x.username,256)&&boundedString(x.password,4096)):validCredentials(x.credentials))}const keys={website:['name','url','description','tags','groupId','pinned','pinRank'],note:['title','body','tags','attachmentIds','groupId','pinned','pinRank']}[type];if(!keys||Object.keys(x).some(k=>!keys.includes(k)))return false;return keys.filter(k=>!['attachmentIds','groupId','pinned','pinRank'].includes(k)).every(k=>k in x)&&Array.isArray(x.tags)&&(type!=='note'||(x.attachmentIds===undefined||(Array.isArray(x.attachmentIds)&&x.attachmentIds.length<=20&&x.attachmentIds.every(attachmentIdValid))))}
export const validAttachmentId=x=>typeof x==='string'&&/^[a-zA-Z0-9_-]{8,80}$/.test(x);
export function attachmentAad(id){if(!validAttachmentId(id))throw new TypeError('invalid_attachment_id');return new TextEncoder().encode(`pass-vault-v2:attachment:1:${id}`)}
export function validateAttachmentMetadata(x){if(!plainObject(x)||Object.keys(x).some(k=>!['name','mime','size','category','noteId','contentIv','groupId','pinned','pinRank'].includes(k))||('pinned'in x&&typeof x.pinned!=='boolean')||('pinRank'in x&&(!Number.isSafeInteger(x.pinRank)||x.pinRank<0||x.pinRank>1000000||x.pinned!==true)))return false;return typeof x.name==='string'&&x.name.length>0&&x.name.length<=255&&!/[\p{Cc}\p{Cf}]/u.test(x.name)&&typeof x.mime==='string'&&x.mime.length<=255&&Number.isSafeInteger(x.size)&&x.size>=0&&ATTACHMENT_CATEGORIES.includes(x.category)&&x.size<=ATTACHMENT_LIMITS[x.category]&&(x.noteId===undefined||(validAttachmentId(x.noteId)&&x.category==='image'))&&(x.groupId===undefined||ID_RE.test(x.groupId))&&typeof x.contentIv==='string'&&/^[A-Za-z0-9+/]{16}$/.test(x.contentIv)}
export function validAttachmentEnvelope(x){return plainObject(x)&&Object.keys(x).length===3&&x.version===1&&typeof x.iv==='string'&&x.iv.length>0&&x.iv.length<1000&&typeof x.ciphertext==='string'&&x.ciphertext.length>0&&x.ciphertext.length<2_000_000}
export function validAttachmentRecord(x){return plainObject(x)&&Object.keys(x).every(k=>['id','metadata','ciphertextSize','createdAt','updatedAt'].includes(k))&&validAttachmentId(x.id)&&validAttachmentEnvelope(x.metadata)&&Number.isSafeInteger(x.ciphertextSize)&&x.ciphertextSize>=16&&x.ciphertextSize<=MAX_ATTACHMENT_CIPHERTEXT}