import {rm,mkdir,cp} from 'node:fs/promises';
await rm('dist',{recursive:true,force:true});
await mkdir('dist',{recursive:true});
await cp('public','dist',{recursive:true});
await mkdir('dist/shared',{recursive:true});
await cp('shared/contract.mjs','dist/shared/contract.mjs');
await mkdir('dist/vendor',{recursive:true});
await cp('node_modules/pdfjs-dist/build/pdf.min.mjs','dist/vendor/pdf.min.mjs');
await cp('node_modules/pdfjs-dist/build/pdf.worker.min.mjs','dist/vendor/pdf.worker.min.mjs');
console.log('构建完成: dist/');
